# Printing and obtaining all results:

In [2]:
import os
import pandas as pd

original_path = os.getcwd()

def custom_table_generator(result):
    metrics = list(result.columns)[1:]

    print(f"\\begin{{tabular}}{{l{'c' * len(metrics)}}}\\toprule")
    print("Dataset & " + " & ".join(metrics) + "\\\\\\midrule")
    for _, row in result.iterrows():
        values = [row["Dataset"]]
        for metric in result.columns[1:]:
            value = row[metric]
            if pd.isna(value):
                values.append("-")
            else:
                values.append(f"{value}")
        print(" & ".join(values) + "\\\\")
    print("\\bottomrule\\end{tabular}")

Getting results:

In [3]:
folder_path = os.path.dirname(original_path) + "/results/final_tables/"

Marginal coverage:

In [4]:
output_cover = pd.read_pickle(folder_path + "/result_cover.pkl")
output_cover

,Dataset,credo_GP,credo_QNN,credo_BART_adap,credo_BART_fixed,credo_GP_fixed,credo_QNN_fixed,credo_QNN_ens,credo_QNN_ens_fixed,cqr,cqrr,uacqrs,uacqrp,EPIC
0,airfoil,0.904 (0.006),0.905 (0.008),0.904 (0.006),0.904 (0.006),0.903 (0.009),0.903 (0.009),0.901 (0.008),0.904 (0.006),0.903 (0.008),0.878 (0.007),0.908 (0.008),0.904 (0.009),0.911 (0.009)
1,bike,0.9 (0.004),0.9 (0.003),0.9 (0.004),0.901 (0.003),0.899 (0.003),0.9 (0.003),0.899 (0.003),0.9 (0.004),0.902 (0.003),0.899 (0.003),0.903 (0.003),0.902 (0.004),0.901 (0.004)
2,concrete,0.899 (0.008),0.896 (0.01),0.894 (0.01),0.898 (0.01),0.894 (0.011),0.892 (0.011),0.896 (0.009),0.899 (0.008),0.9 (0.008),0.872 (0.01),0.896 (0.009),0.894 (0.008),0.908 (0.012)
3,cycle,0.896 (0.003),0.898 (0.003),0.896 (0.004),0.896 (0.004),0.898 (0.003),0.897 (0.003),0.897 (0.003),0.896 (0.003),0.895 (0.003),0.895 (0.003),0.895 (0.004),0.898 (0.003),0.896 (0.005)
4,electric,0.9 (0.003),0.897 (0.004),0.901 (0.003),0.902 (0.003),0.899 (0.003),0.9 (0.003),0.898 (0.003),0.9 (0.003),0.902 (0.003),0.899 (0.003),0.9 (0.003),0.9 (0.004),0.905 (0.004)
5,homes,0.9 (0.002),0.903 (0.003),0.903 (0.002),0.904 (0.002),0.903 (0.002),0.903 (0.002),0.901 (0.003),0.9 (0.002),0.904 (0.002),0.904 (0.002),0.903 (0.002),0.904 (0.002),0.901 (0.003)
6,meps19,0.9 (0.002),0.898 (0.002),0.899 (0.003),0.899 (0.003),0.9 (0.003),0.901 (0.003),0.9 (0.002),0.9 (0.002),0.899 (0.002),0.895 (0.002),0.901 (0.002),0.923 (0.011),0.898 (0.004)
7,news,0.899 (0.002),0.9 (0.002),0.901 (0.002),0.901 (0.002),0.9 (0.002),0.901 (0.002),0.9 (0.002),0.899 (0.002),0.9 (0.002),0.9 (0.002),0.9 (0.002),0.9 (0.002),0.902 (0.003)
8,protein,0.9 (0.002),0.901 (0.001),0.9 (0.002),0.9 (0.002),0.901 (0.001),0.901 (0.001),0.901 (0.002),0.9 (0.002),0.899 (0.001),0.899 (0.001),0.899 (0.001),0.9 (0.002),0.898 (0.004)
9,superconductivity,0.9 (0.002),0.903 (0.002),0.901 (0.002),0.903 (0.003),0.902 (0.002),0.903 (0.002),0.901 (0.002),0.9 (0.002),0.901 (0.003),0.901 (0.003),0.901 (0.003),0.902 (0.002),0.902 (0.003)
10,winered,0.906 (0.006),0.903 (0.006),0.899 (0.006),0.9 (0.007),0.9 (0.007),0.9 (0.007),0.902 (0.006),0.906 (0.006),0.902 (0.006),0.896 (0.007),0.903 (0.008),0.903 (0.006),0.908 (0.008)
11,winewhite,0.874 (0.06),0.902 (0.005),0.902 (0.005),0.902 (0.004),0.9 (0.005),0.9 (0.004),0.901 (0.005),0.874 (0.06),0.904 (0.004),0.903 (0.004),0.902 (0.004),0.903 (0.004),0.906 (0.005)

In [5]:
custom_table_generator(output_cover)

\begin{tabular}{lccccccccccccc}\toprule
Dataset & credo_GP & credo_QNN & credo_BART_adap & credo_BART_fixed & credo_GP_fixed & credo_QNN_fixed & credo_QNN_ens & credo_QNN_ens_fixed & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
airfoil & 0.904 (0.006) & 0.905 (0.008) & 0.904 (0.006) & 0.904 (0.006) & 0.903 (0.009) & 0.903 (0.009) & 0.901 (0.008) & 0.904 (0.006) & 0.903 (0.008) & 0.878 (0.007) & 0.908 (0.008) & 0.904 (0.009) & 0.911 (0.009)\\
bike & 0.9 (0.004) & 0.9 (0.003) & 0.9 (0.004) & 0.901 (0.003) & 0.899 (0.003) & 0.9 (0.003) & 0.899 (0.003) & 0.9 (0.004) & 0.902 (0.003) & 0.899 (0.003) & 0.903 (0.003) & 0.902 (0.004) & 0.901 (0.004)\\
concrete & 0.899 (0.008) & 0.896 (0.01) & 0.894 (0.01) & 0.898 (0.01) & 0.894 (0.011) & 0.892 (0.011) & 0.896 (0.009) & 0.899 (0.008) & 0.9 (0.008) & 0.872 (0.01) & 0.896 (0.009) & 0.894 (0.008) & 0.908 (0.012)\\
cycle & 0.896 (0.003) & 0.898 (0.003) & 0.896 (0.004) & 0.896 (0.004) & 0.898 (0.003) & 0.897 (0.003) & 0.897 (0.003) & 0.896 (0.003) & 0.895 (0.003) & 0.895 (0.003) & 0.895 (0.004) & 0.898 (0.003) & 0.896 (0.005)\\
electric & 0.9 (0.003) & 0.897 (0.004) & 0.901 (0.003) & 0.902 (0.003) & 0.899 (0.003) & 0.9 (0.003) & 0.898 (0.003) & 0.9 (0.003) & 0.902 (0.003) & 0.899 (0.003) & 0.9 (0.003) & 0.9 (0.004) & 0.905 (0.004)\\
homes & 0.9 (0.002) & 0.903 (0.003) & 0.903 (0.002) & 0.904 (0.002) & 0.903 (0.002) & 0.903 (0.002) & 0.901 (0.003) & 0.9 (0.002) & 0.904 (0.002) & 0.904 (0.002) & 0.903 (0.002) & 0.904 (0.002) & 0.901 (0.003)\\
meps19 & 0.9 (0.002) & 0.898 (0.002) & 0.899 (0.003) & 0.899 (0.003) & 0.9 (0.003) & 0.901 (0.003) & 0.9 (0.002) & 0.9 (0.002) & 0.899 (0.002) & 0.895 (0.002) & 0.901 (0.002) & 0.923 (0.011) & 0.898 (0.004)\\
news & 0.899 (0.002) & 0.9 (0.002) & 0.901 (0.002) & 0.901 (0.002) & 0.9 (0.002) & 0.901 (0.002) & 0.9 (0.002) & 0.899 (0.002) & 0.9 (0.002) & 0.9 (0.002) & 0.9 (0.002) & 0.9 (0.002) & 0.902 (0.003)\\
protein & 0.9 (0.002) & 0.901 (0.001) & 0.9 (0.002) & 0.9 (0.002) & 0.901 (0.001) & 0.901 (0.001) & 0.901 (0.002) & 0.9 (0.002) & 0.899 (0.001) & 0.899 (0.001) & 0.899 (0.001) & 0.9 (0.002) & 0.898 (0.004)\\
superconductivity & 0.9 (0.002) & 0.903 (0.002) & 0.901 (0.002) & 0.903 (0.003) & 0.902 (0.002) & 0.903 (0.002) & 0.901 (0.002) & 0.9 (0.002) & 0.901 (0.003) & 0.901 (0.003) & 0.901 (0.003) & 0.902 (0.002) & 0.902 (0.003)\\
winered & 0.906 (0.006) & 0.903 (0.006) & 0.899 (0.006) & 0.9 (0.007) & 0.9 (0.007) & 0.9 (0.007) & 0.902 (0.006) & 0.906 (0.006) & 0.902 (0.006) & 0.896 (0.007) & 0.903 (0.008) & 0.903 (0.006) & 0.908 (0.008)\\
winewhite & 0.874 (0.06) & 0.902 (0.005) & 0.902 (0.005) & 0.902 (0.004) & 0.9 (0.005) & 0.9 (0.004) & 0.901 (0.005) & 0.874 (0.06) & 0.904 (0.004) & 0.903 (0.004) & 0.902 (0.004) & 0.903 (0.004) & 0.906 (0.005)\\
\bottomrule\end{tabular}

Average Interval Score Length:

In [6]:
output_aisl = pd.read_pickle(folder_path + "/result_aisl.pkl")
output_aisl

,Dataset,credo_GP,credo_QNN,credo_BART_adap,credo_BART_fixed,credo_GP_fixed,credo_QNN_fixed,credo_QNN_ens,credo_QNN_ens_fixed,cqr,cqrr,uacqrs,uacqrp,EPIC
0,airfoil,12.866 (0.407),12.955 (0.475),14.399 (0.262),14.703 (0.257),12.917 (0.385),13.108 (0.398),13.116 (0.496),12.866 (0.407),11.685 (0.324),18.245 (1.134),14.995 (0.427),16.754 (0.561),10.878 (0.321)
1,bike,592.89 (6.582),220.721 (2.997),467.217 (5.464),458.978 (4.745),206.132 (1.588),221.338 (1.786),280.945 (3.789),592.89 (6.582),191.179 (2.158),194.027 (1.76),198.03 (2.117),224.987 (3.413),189.624 (2.223)
2,concrete,28.559 (0.854),29.977 (0.829),27.378 (0.613),27.642 (0.625),30.92 (1.241),31.318 (1.266),30.771 (0.778),28.559 (0.854),30.904 (0.889),44.455 (2.79),42.17 (1.378),45.048 (1.825),29.329 (0.734)
3,cycle,17.337 (0.153),17.543 (0.166),17.413 (0.157),17.394 (0.155),16.963 (0.132),17.031 (0.137),18.169 (0.203),17.337 (0.153),15.301 (0.164),15.389 (0.167),15.632 (0.164),16.301 (0.224),15.316 (0.164)
4,electric,0.047 (0.0),0.036 (0.001),0.064 (0.0),0.064 (0.0),0.035 (0.0),0.036 (0.0),0.037 (0.0),0.047 (0.0),0.044 (0.0),0.047 (0.0),0.054 (0.001),0.06 (0.001),0.043 (0.0)
5,homes,701505.641 (8355.222),439949.2 (4324.769),647081.599 (6300.405),669660.203 (6885.342),408257.749 (4200.641),411668.004 (4134.583),467701.564 (4980.084),701505.641 (8355.222),428142.976 (5111.253),425948.712 (4770.94),432517.736 (4954.39),443312.873 (5678.878),418461.389 (4438.439)
6,meps19,84.924 (2.352),56.479 (1.354),76.798 (1.648),80.007 (1.676),54.752 (1.449),55.45 (1.402),58.515 (1.277),84.924 (2.352),58.824 (2.093),58.594 (2.073),56.453 (1.846),58.815 (2.035),57.998 (2.071)
7,news,29896.117 (772.321),27229.12 (923.218),34102.88 (547.806),36491.383 (505.53),26591.025 (913.653),26686.955 (835.557),27996.443 (898.97),29896.117 (772.321),26026.024 (753.946),26055.287 (752.186),25889.398 (740.077),25739.94 (750.319),26144.181 (756.332)
8,protein,19.174 (0.062),15.274 (0.053),19.559 (0.082),19.649 (0.082),14.945 (0.042),15.084 (0.038),15.816 (0.044),19.174 (0.062),15.171 (0.048),15.169 (0.048),15.325 (0.045),15.769 (0.051),15.136 (0.046)
9,superconductivity,75.071 (0.469),45.156 (0.383),60.906 (0.404),65.874 (0.471),44.064 (0.272),45.501 (0.255),50.796 (0.398),75.071 (0.469),43.762 (0.354),43.787 (0.341),45.263 (0.39),47.569 (0.361),43.682 (0.335)
10,winered,2.583 (0.05),2.753 (0.059),2.712 (0.041),2.733 (0.043),2.687 (0.051),2.696 (0.051),2.808 (0.057),2.583 (0.05),3.069 (0.066),3.486 (0.143),2.865 (0.058),2.937 (0.075),2.837 (0.054)
11,winewhite,2.775 (0.036),2.954 (0.034),3.043 (0.033),3.052 (0.033),2.918 (0.035),2.929 (0.032),3.024 (0.025),2.775 (0.036),3.054 (0.031),3.119 (0.035),2.995 (0.027),3.077 (0.032),2.962 (0.031)

In [7]:
custom_table_generator(output_aisl)

\begin{tabular}{lccccccccccccc}\toprule
Dataset & credo_GP & credo_QNN & credo_BART_adap & credo_BART_fixed & credo_GP_fixed & credo_QNN_fixed & credo_QNN_ens & credo_QNN_ens_fixed & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
airfoil & 12.866 (0.407) & 12.955 (0.475) & 14.399 (0.262) & 14.703 (0.257) & 12.917 (0.385) & 13.108 (0.398) & 13.116 (0.496) & 12.866 (0.407) & 11.685 (0.324) & 18.245 (1.134) & 14.995 (0.427) & 16.754 (0.561) & 10.878 (0.321)\\
bike & 592.89 (6.582) & 220.721 (2.997) & 467.217 (5.464) & 458.978 (4.745) & 206.132 (1.588) & 221.338 (1.786) & 280.945 (3.789) & 592.89 (6.582) & 191.179 (2.158) & 194.027 (1.76) & 198.03 (2.117) & 224.987 (3.413) & 189.624 (2.223)\\
concrete & 28.559 (0.854) & 29.977 (0.829) & 27.378 (0.613) & 27.642 (0.625) & 30.92 (1.241) & 31.318 (1.266) & 30.771 (0.778) & 28.559 (0.854) & 30.904 (0.889) & 44.455 (2.79) & 42.17 (1.378) & 45.048 (1.825) & 29.329 (0.734)\\
cycle & 17.337 (0.153) & 17.543 (0.166) & 17.413 (0.157) & 17.394 (0.155) & 16.963 (0.132) & 17.031 (0.137) & 18.169 (0.203) & 17.337 (0.153) & 15.301 (0.164) & 15.389 (0.167) & 15.632 (0.164) & 16.301 (0.224) & 15.316 (0.164)\\
electric & 0.047 (0.0) & 0.036 (0.001) & 0.064 (0.0) & 0.064 (0.0) & 0.035 (0.0) & 0.036 (0.0) & 0.037 (0.0) & 0.047 (0.0) & 0.044 (0.0) & 0.047 (0.0) & 0.054 (0.001) & 0.06 (0.001) & 0.043 (0.0)\\
homes & 701505.641 (8355.222) & 439949.2 (4324.769) & 647081.599 (6300.405) & 669660.203 (6885.342) & 408257.749 (4200.641) & 411668.004 (4134.583) & 467701.564 (4980.084) & 701505.641 (8355.222) & 428142.976 (5111.253) & 425948.712 (4770.94) & 432517.736 (4954.39) & 443312.873 (5678.878) & 418461.389 (4438.439)\\
meps19 & 84.924 (2.352) & 56.479 (1.354) & 76.798 (1.648) & 80.007 (1.676) & 54.752 (1.449) & 55.45 (1.402) & 58.515 (1.277) & 84.924 (2.352) & 58.824 (2.093) & 58.594 (2.073) & 56.453 (1.846) & 58.815 (2.035) & 57.998 (2.071)\\
news & 29896.117 (772.321) & 27229.12 (923.218) & 34102.88 (547.806) & 36491.383 (505.53) & 26591.025 (913.653) & 26686.955 (835.557) & 27996.443 (898.97) & 29896.117 (772.321) & 26026.024 (753.946) & 26055.287 (752.186) & 25889.398 (740.077) & 25739.94 (750.319) & 26144.181 (756.332)\\
protein & 19.174 (0.062) & 15.274 (0.053) & 19.559 (0.082) & 19.649 (0.082) & 14.945 (0.042) & 15.084 (0.038) & 15.816 (0.044) & 19.174 (0.062) & 15.171 (0.048) & 15.169 (0.048) & 15.325 (0.045) & 15.769 (0.051) & 15.136 (0.046)\\
superconductivity & 75.071 (0.469) & 45.156 (0.383) & 60.906 (0.404) & 65.874 (0.471) & 44.064 (0.272) & 45.501 (0.255) & 50.796 (0.398) & 75.071 (0.469) & 43.762 (0.354) & 43.787 (0.341) & 45.263 (0.39) & 47.569 (0.361) & 43.682 (0.335)\\
winered & 2.583 (0.05) & 2.753 (0.059) & 2.712 (0.041) & 2.733 (0.043) & 2.687 (0.051) & 2.696 (0.051) & 2.808 (0.057) & 2.583 (0.05) & 3.069 (0.066) & 3.486 (0.143) & 2.865 (0.058) & 2.937 (0.075) & 2.837 (0.054)\\
winewhite & 2.775 (0.036) & 2.954 (0.034) & 3.043 (0.033) & 3.052 (0.033) & 2.918 (0.035) & 2.929 (0.032) & 3.024 (0.025) & 2.775 (0.036) & 3.054 (0.031) & 3.119 (0.035) & 2.995 (0.027) & 3.077 (0.032) & 2.962 (0.031)\\
\bottomrule\end{tabular}

Interval length:

In [8]:
output_il = pd.read_pickle(folder_path + "/result_il.pkl")
output_il

,Dataset,credo_GP,credo_QNN,credo_BART_adap,credo_BART_fixed,credo_GP_fixed,credo_QNN_fixed,credo_QNN_ens,credo_QNN_ens_fixed,cqr,cqrr,uacqrs,uacqrp,EPIC
0,airfoil,9.239 (0.198),10.442 (0.33),11.791 (0.152),12.228 (0.16),10.333 (0.217),10.506 (0.203),10.534 (0.315),9.239 (0.198),8.618 (0.217),11.851 (0.704),12.51 (0.433),14.188 (0.582),8.546 (0.223)
1,bike,379.076 (3.913),205.414 (3.234),315.197 (2.829),338.006 (3.762),187.141 (1.419),205.293 (1.77),268.967 (4.186),379.076 (3.913),155.016 (1.792),164.513 (1.859),167.528 (1.811),195.565 (3.331),154.809 (1.639)
2,concrete,20.848 (0.366),23.271 (0.728),21.468 (0.338),21.914 (0.324),23.9 (0.946),24.386 (0.93),24.381 (0.696),20.848 (0.366),21.764 (0.48),29.139 (1.226),33.848 (1.712),36.716 (2.178),21.909 (0.789)
3,cycle,12.831 (0.081),13.58 (0.116),13.221 (0.092),13.184 (0.079),12.983 (0.084),13.039 (0.086),14.067 (0.19),12.831 (0.081),11.563 (0.063),11.64 (0.069),12.06 (0.107),12.779 (0.229),11.563 (0.125)
4,electric,0.034 (0.0),0.029 (0.0),0.051 (0.0),0.052 (0.0),0.027 (0.0),0.027 (0.0),0.029 (0.0),0.034 (0.0),0.034 (0.0),0.037 (0.0),0.045 (0.001),0.051 (0.001),0.035 (0.0)
5,homes,401949.832 (2481.065),360000.229 (3213.803),484456.113 (4847.554),520579.859 (5514.156),320199.232 (1979.424),327537.982 (2153.976),392677.171 (4061.431),401949.832 (2481.065),294888.77 (1749.982),306433.944 (1995.245),305396.488 (2276.398),328254.429 (3049.844),311437.095 (3632.106)
6,meps19,27.584 (0.469),37.539 (0.779),47.868 (1.249),53.913 (1.48),33.924 (0.641),36.47 (0.643),42.68 (0.936),27.584 (0.469),23.057 (0.334),23.342 (0.331),31.532 (0.403),33.978 (0.706),25.57 (0.56)
7,news,9086.411 (93.331),13340.984 (720.693),19225.487 (404.101),22457.759 (546.158),11763.342 (646.647),12823.991 (549.19),15719.92 (809.408),9086.411 (93.331),8666.661 (50.974),8749.045 (48.299),10283.082 (70.233),9962.42 (61.94),9011.358 (87.247)
8,protein,15.371 (0.047),13.808 (0.046),15.319 (0.044),15.278 (0.043),13.322 (0.022),13.629 (0.022),14.637 (0.044),15.371 (0.047),12.992 (0.026),13.004 (0.026),13.442 (0.036),14.091 (0.056),13.031 (0.051)
9,superconductivity,54.408 (0.221),39.237 (0.418),51.542 (0.251),59.388 (0.455),38.074 (0.179),40.668 (0.188),46.789 (0.416),54.408 (0.221),35.852 (0.181),36.759 (0.167),38.498 (0.367),41.368 (0.298),36.34 (0.298)
10,winered,1.94 (0.03),2.135 (0.043),2.052 (0.028),2.059 (0.03),2.035 (0.031),2.074 (0.029),2.247 (0.034),1.94 (0.03),2.091 (0.064),2.222 (0.095),2.041 (0.054),2.11 (0.091),2.004 (0.067)
11,winewhite,2.04 (0.017),2.272 (0.026),2.279 (0.018),2.287 (0.016),2.189 (0.017),2.23 (0.016),2.428 (0.023),2.04 (0.017),2.144 (0.023),2.17 (0.028),2.224 (0.013),2.226 (0.012),2.131 (0.028)

In [9]:
custom_table_generator(output_il)

\begin{tabular}{lccccccccccccc}\toprule
Dataset & credo_GP & credo_QNN & credo_BART_adap & credo_BART_fixed & credo_GP_fixed & credo_QNN_fixed & credo_QNN_ens & credo_QNN_ens_fixed & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
airfoil & 9.239 (0.198) & 10.442 (0.33) & 11.791 (0.152) & 12.228 (0.16) & 10.333 (0.217) & 10.506 (0.203) & 10.534 (0.315) & 9.239 (0.198) & 8.618 (0.217) & 11.851 (0.704) & 12.51 (0.433) & 14.188 (0.582) & 8.546 (0.223)\\
bike & 379.076 (3.913) & 205.414 (3.234) & 315.197 (2.829) & 338.006 (3.762) & 187.141 (1.419) & 205.293 (1.77) & 268.967 (4.186) & 379.076 (3.913) & 155.016 (1.792) & 164.513 (1.859) & 167.528 (1.811) & 195.565 (3.331) & 154.809 (1.639)\\
concrete & 20.848 (0.366) & 23.271 (0.728) & 21.468 (0.338) & 21.914 (0.324) & 23.9 (0.946) & 24.386 (0.93) & 24.381 (0.696) & 20.848 (0.366) & 21.764 (0.48) & 29.139 (1.226) & 33.848 (1.712) & 36.716 (2.178) & 21.909 (0.789)\\
cycle & 12.831 (0.081) & 13.58 (0.116) & 13.221 (0.092) & 13.184 (0.079) & 12.983 (0.084) & 13.039 (0.086) & 14.067 (0.19) & 12.831 (0.081) & 11.563 (0.063) & 11.64 (0.069) & 12.06 (0.107) & 12.779 (0.229) & 11.563 (0.125)\\
electric & 0.034 (0.0) & 0.029 (0.0) & 0.051 (0.0) & 0.052 (0.0) & 0.027 (0.0) & 0.027 (0.0) & 0.029 (0.0) & 0.034 (0.0) & 0.034 (0.0) & 0.037 (0.0) & 0.045 (0.001) & 0.051 (0.001) & 0.035 (0.0)\\
homes & 401949.832 (2481.065) & 360000.229 (3213.803) & 484456.113 (4847.554) & 520579.859 (5514.156) & 320199.232 (1979.424) & 327537.982 (2153.976) & 392677.171 (4061.431) & 401949.832 (2481.065) & 294888.77 (1749.982) & 306433.944 (1995.245) & 305396.488 (2276.398) & 328254.429 (3049.844) & 311437.095 (3632.106)\\
meps19 & 27.584 (0.469) & 37.539 (0.779) & 47.868 (1.249) & 53.913 (1.48) & 33.924 (0.641) & 36.47 (0.643) & 42.68 (0.936) & 27.584 (0.469) & 23.057 (0.334) & 23.342 (0.331) & 31.532 (0.403) & 33.978 (0.706) & 25.57 (0.56)\\
news & 9086.411 (93.331) & 13340.984 (720.693) & 19225.487 (404.101) & 22457.759 (546.158) & 11763.342 (646.647) & 12823.991 (549.19) & 15719.92 (809.408) & 9086.411 (93.331) & 8666.661 (50.974) & 8749.045 (48.299) & 10283.082 (70.233) & 9962.42 (61.94) & 9011.358 (87.247)\\
protein & 15.371 (0.047) & 13.808 (0.046) & 15.319 (0.044) & 15.278 (0.043) & 13.322 (0.022) & 13.629 (0.022) & 14.637 (0.044) & 15.371 (0.047) & 12.992 (0.026) & 13.004 (0.026) & 13.442 (0.036) & 14.091 (0.056) & 13.031 (0.051)\\
superconductivity & 54.408 (0.221) & 39.237 (0.418) & 51.542 (0.251) & 59.388 (0.455) & 38.074 (0.179) & 40.668 (0.188) & 46.789 (0.416) & 54.408 (0.221) & 35.852 (0.181) & 36.759 (0.167) & 38.498 (0.367) & 41.368 (0.298) & 36.34 (0.298)\\
winered & 1.94 (0.03) & 2.135 (0.043) & 2.052 (0.028) & 2.059 (0.03) & 2.035 (0.031) & 2.074 (0.029) & 2.247 (0.034) & 1.94 (0.03) & 2.091 (0.064) & 2.222 (0.095) & 2.041 (0.054) & 2.11 (0.091) & 2.004 (0.067)\\
winewhite & 2.04 (0.017) & 2.272 (0.026) & 2.279 (0.018) & 2.287 (0.016) & 2.189 (0.017) & 2.23 (0.016) & 2.428 (0.023) & 2.04 (0.017) & 2.144 (0.023) & 2.17 (0.028) & 2.224 (0.013) & 2.226 (0.012) & 2.131 (0.028)\\
\bottomrule\end{tabular}

Pearson Correlation:

In [10]:
output_pcor = pd.read_pickle(folder_path + "/result_pcorr.pkl")
output_pcor

,Dataset,credo_GP,credo_QNN,credo_BART_adap,credo_BART_fixed,credo_GP_fixed,credo_QNN_fixed,credo_QNN_ens,credo_QNN_ens_fixed,cqr,cqrr,uacqrs,uacqrp,EPIC
0,airfoil,0.094 (0.011),0.058 (0.014),0.08 (0.02),0.048 (0.013),0.068 (0.018),0.069 (0.017),0.084 (0.021),0.094 (0.011),0.263 (0.029),0.527 (0.019),0.061 (0.018),0.062 (0.019),0.151 (0.026)
1,bike,0.114 (0.004),0.249 (0.007),0.202 (0.012),0.101 (0.016),0.19 (0.008),0.234 (0.007),0.306 (0.007),0.114 (0.004),0.038 (0.012),0.121 (0.012),0.032 (0.01),0.03 (0.01),0.039 (0.011)
2,concrete,0.051 (0.017),0.107 (0.02),0.044 (0.015),0.053 (0.018),0.056 (0.013),0.062 (0.016),0.155 (0.023),0.051 (0.017),0.191 (0.034),0.525 (0.026),0.092 (0.025),0.106 (0.024),0.121 (0.027)
3,cycle,0.058 (0.005),0.132 (0.007),0.06 (0.01),0.053 (0.011),0.073 (0.008),0.085 (0.008),0.183 (0.009),0.058 (0.005),0.055 (0.009),0.121 (0.01),0.036 (0.008),0.027 (0.007),0.048 (0.01)
4,electric,0.019 (0.004),0.094 (0.01),0.066 (0.009),0.108 (0.009),0.061 (0.008),0.032 (0.007),0.124 (0.01),0.019 (0.004),0.082 (0.011),0.301 (0.012),0.045 (0.009),0.064 (0.011),0.103 (0.012)
5,homes,0.096 (0.007),0.079 (0.004),0.022 (0.007),0.025 (0.008),0.046 (0.005),0.058 (0.005),0.102 (0.004),0.096 (0.007),0.053 (0.009),0.018 (0.005),0.042 (0.009),0.026 (0.007),0.021 (0.005)
6,meps19,0.363 (0.007),0.07 (0.008),0.073 (0.007),0.088 (0.007),0.044 (0.008),0.046 (0.009),0.083 (0.01),0.363 (0.007),0.089 (0.008),0.019 (0.006),0.044 (0.008),0.058 (0.021),0.023 (0.007)
7,news,0.061 (0.005),0.037 (0.008),0.201 (0.006),0.235 (0.007),0.04 (0.007),0.043 (0.008),0.031 (0.009),0.061 (0.005),0.016 (0.005),0.065 (0.007),0.021 (0.005),0.013 (0.002),0.042 (0.009)
8,protein,0.021 (0.002),0.022 (0.006),0.04 (0.004),0.037 (0.004),0.028 (0.006),0.021 (0.004),0.035 (0.008),0.021 (0.002),0.028 (0.004),0.013 (0.004),0.046 (0.005),0.047 (0.005),0.035 (0.006)
9,superconductivity,0.234 (0.003),0.123 (0.009),0.057 (0.01),0.304 (0.011),0.105 (0.008),0.166 (0.008),0.217 (0.007),0.234 (0.003),0.051 (0.01),0.053 (0.007),0.038 (0.008),0.024 (0.006),0.027 (0.007)
10,winered,0.044 (0.011),0.124 (0.018),0.051 (0.015),0.062 (0.02),0.088 (0.021),0.106 (0.024),0.162 (0.021),0.044 (0.011),0.286 (0.034),0.405 (0.036),0.074 (0.017),0.093 (0.02),0.094 (0.028)
11,winewhite,0.034 (0.007),0.06 (0.015),0.083 (0.014),0.088 (0.013),0.035 (0.01),0.041 (0.011),0.12 (0.019),0.034 (0.007),0.13 (0.014),0.202 (0.021),0.029 (0.008),0.115 (0.02),0.056 (0.013)

In [11]:
custom_table_generator(output_pcor)

\begin{tabular}{lccccccccccccc}\toprule
Dataset & credo_GP & credo_QNN & credo_BART_adap & credo_BART_fixed & credo_GP_fixed & credo_QNN_fixed & credo_QNN_ens & credo_QNN_ens_fixed & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
airfoil & 0.094 (0.011) & 0.058 (0.014) & 0.08 (0.02) & 0.048 (0.013) & 0.068 (0.018) & 0.069 (0.017) & 0.084 (0.021) & 0.094 (0.011) & 0.263 (0.029) & 0.527 (0.019) & 0.061 (0.018) & 0.062 (0.019) & 0.151 (0.026)\\
bike & 0.114 (0.004) & 0.249 (0.007) & 0.202 (0.012) & 0.101 (0.016) & 0.19 (0.008) & 0.234 (0.007) & 0.306 (0.007) & 0.114 (0.004) & 0.038 (0.012) & 0.121 (0.012) & 0.032 (0.01) & 0.03 (0.01) & 0.039 (0.011)\\
concrete & 0.051 (0.017) & 0.107 (0.02) & 0.044 (0.015) & 0.053 (0.018) & 0.056 (0.013) & 0.062 (0.016) & 0.155 (0.023) & 0.051 (0.017) & 0.191 (0.034) & 0.525 (0.026) & 0.092 (0.025) & 0.106 (0.024) & 0.121 (0.027)\\
cycle & 0.058 (0.005) & 0.132 (0.007) & 0.06 (0.01) & 0.053 (0.011) & 0.073 (0.008) & 0.085 (0.008) & 0.183 (0.009) & 0.058 (0.005) & 0.055 (0.009) & 0.121 (0.01) & 0.036 (0.008) & 0.027 (0.007) & 0.048 (0.01)\\
electric & 0.019 (0.004) & 0.094 (0.01) & 0.066 (0.009) & 0.108 (0.009) & 0.061 (0.008) & 0.032 (0.007) & 0.124 (0.01) & 0.019 (0.004) & 0.082 (0.011) & 0.301 (0.012) & 0.045 (0.009) & 0.064 (0.011) & 0.103 (0.012)\\
homes & 0.096 (0.007) & 0.079 (0.004) & 0.022 (0.007) & 0.025 (0.008) & 0.046 (0.005) & 0.058 (0.005) & 0.102 (0.004) & 0.096 (0.007) & 0.053 (0.009) & 0.018 (0.005) & 0.042 (0.009) & 0.026 (0.007) & 0.021 (0.005)\\
meps19 & 0.363 (0.007) & 0.07 (0.008) & 0.073 (0.007) & 0.088 (0.007) & 0.044 (0.008) & 0.046 (0.009) & 0.083 (0.01) & 0.363 (0.007) & 0.089 (0.008) & 0.019 (0.006) & 0.044 (0.008) & 0.058 (0.021) & 0.023 (0.007)\\
news & 0.061 (0.005) & 0.037 (0.008) & 0.201 (0.006) & 0.235 (0.007) & 0.04 (0.007) & 0.043 (0.008) & 0.031 (0.009) & 0.061 (0.005) & 0.016 (0.005) & 0.065 (0.007) & 0.021 (0.005) & 0.013 (0.002) & 0.042 (0.009)\\
protein & 0.021 (0.002) & 0.022 (0.006) & 0.04 (0.004) & 0.037 (0.004) & 0.028 (0.006) & 0.021 (0.004) & 0.035 (0.008) & 0.021 (0.002) & 0.028 (0.004) & 0.013 (0.004) & 0.046 (0.005) & 0.047 (0.005) & 0.035 (0.006)\\
superconductivity & 0.234 (0.003) & 0.123 (0.009) & 0.057 (0.01) & 0.304 (0.011) & 0.105 (0.008) & 0.166 (0.008) & 0.217 (0.007) & 0.234 (0.003) & 0.051 (0.01) & 0.053 (0.007) & 0.038 (0.008) & 0.024 (0.006) & 0.027 (0.007)\\
winered & 0.044 (0.011) & 0.124 (0.018) & 0.051 (0.015) & 0.062 (0.02) & 0.088 (0.021) & 0.106 (0.024) & 0.162 (0.021) & 0.044 (0.011) & 0.286 (0.034) & 0.405 (0.036) & 0.074 (0.017) & 0.093 (0.02) & 0.094 (0.028)\\
winewhite & 0.034 (0.007) & 0.06 (0.015) & 0.083 (0.014) & 0.088 (0.013) & 0.035 (0.01) & 0.041 (0.011) & 0.12 (0.019) & 0.034 (0.007) & 0.13 (0.014) & 0.202 (0.021) & 0.029 (0.008) & 0.115 (0.02) & 0.056 (0.013)\\
\bottomrule\end{tabular}

Outlier coverage:

In [ ]:
output_cover = pd.read_pickle(folder_path + "/result_cover_outlier.pkl")
output_cover

,Dataset,credo_GP,credo_QNN,credo_BART_adap,credo_BART_fixed,credo_GP_fixed,credo_QNN_fixed,credo_QNN_ens,credo_QNN_ens_fixed,cqr,cqrr,uacqrs,uacqrp,EPIC
0,airfoil,0.868 (0.042),0.918 (0.034),0.891 (0.031),0.884 (0.038),0.868 (0.042),0.909 (0.036),0.91 (0.033),0.902 (0.03),0.86 (0.055),0.85 (0.052),0.907 (0.039),0.903 (0.034),0.9 (0.046)
1,bike,0.916 (0.009),0.895 (0.013),0.918 (0.009),0.896 (0.011),0.916 (0.009),0.891 (0.013),0.893 (0.01),0.882 (0.011),0.873 (0.009),0.86 (0.01),0.881 (0.011),0.887 (0.01),0.875 (0.01)
2,concrete,0.939 (0.027),0.918 (0.033),0.909 (0.031),0.879 (0.037),0.939 (0.027),0.891 (0.041),0.924 (0.032),0.921 (0.032),0.885 (0.033),0.815 (0.047),0.873 (0.039),0.873 (0.04),0.906 (0.037)
3,cycle,0.916 (0.011),0.901 (0.011),0.912 (0.014),0.897 (0.014),0.916 (0.011),0.884 (0.012),0.893 (0.013),0.888 (0.013),0.852 (0.014),0.843 (0.014),0.858 (0.015),0.878 (0.014),0.863 (0.014)
4,electric,0.898 (0.014),0.884 (0.013),0.904 (0.012),0.901 (0.012),0.898 (0.014),0.897 (0.012),0.897 (0.012),0.902 (0.011),0.911 (0.011),0.904 (0.012),0.897 (0.011),0.9 (0.01),0.914 (0.012)
5,homes,0.875 (0.009),0.919 (0.005),0.899 (0.009),0.89 (0.008),0.875 (0.009),0.918 (0.007),0.911 (0.008),0.908 (0.007),0.892 (0.008),0.898 (0.007),0.89 (0.008),0.901 (0.007),0.903 (0.008)
6,meps19,0.889 (0.009),0.899 (0.008),0.903 (0.009),0.904 (0.008),0.889 (0.009),0.901 (0.009),0.904 (0.009),0.908 (0.007),0.894 (0.009),0.89 (0.01),0.897 (0.008),0.921 (0.015),0.894 (0.01)
7,news,0.858 (0.005),0.914 (0.005),0.947 (0.003),0.947 (0.003),0.858 (0.005),0.911 (0.005),0.912 (0.005),0.914 (0.004),0.885 (0.005),0.899 (0.005),0.893 (0.005),0.901 (0.004),0.904 (0.005)
8,protein,0.905 (0.005),0.902 (0.005),0.898 (0.006),0.896 (0.005),0.905 (0.005),0.902 (0.005),0.899 (0.006),0.898 (0.006),0.887 (0.006),0.886 (0.006),0.886 (0.005),0.89 (0.005),0.893 (0.007)
9,superconductivity,0.864 (0.009),0.9 (0.008),0.924 (0.007),0.949 (0.007),0.864 (0.009),0.913 (0.01),0.902 (0.009),0.912 (0.008),0.874 (0.01),0.889 (0.009),0.871 (0.009),0.88 (0.009),0.88 (0.01)
10,winered,0.89 (0.029),0.915 (0.03),0.89 (0.032),0.887 (0.032),0.89 (0.029),0.915 (0.027),0.91 (0.029),0.917 (0.027),0.808 (0.039),0.775 (0.045),0.854 (0.041),0.848 (0.043),0.854 (0.039)
11,winewhite,0.876 (0.062),0.912 (0.011),0.893 (0.014),0.884 (0.014),0.876 (0.062),0.909 (0.012),0.897 (0.011),0.898 (0.012),0.861 (0.018),0.848 (0.02),0.881 (0.016),0.875 (0.014),0.877 (0.016)

In [ ]:
custom_table_generator(output_cover)

\begin{tabular}{lccccccccccccc}\toprule
Dataset & credo_GP & credo_QNN & credo_BART_adap & credo_BART_fixed & credo_GP_fixed & credo_QNN_fixed & credo_QNN_ens & credo_QNN_ens_fixed & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
airfoil & 0.868 (0.042) & 0.918 (0.034) & 0.891 (0.031) & 0.884 (0.038) & 0.868 (0.042) & 0.909 (0.036) & 0.91 (0.033) & 0.902 (0.03) & 0.86 (0.055) & 0.85 (0.052) & 0.907 (0.039) & 0.903 (0.034) & 0.9 (0.046)\\
bike & 0.916 (0.009) & 0.895 (0.013) & 0.918 (0.009) & 0.896 (0.011) & 0.916 (0.009) & 0.891 (0.013) & 0.893 (0.01) & 0.882 (0.011) & 0.873 (0.009) & 0.86 (0.01) & 0.881 (0.011) & 0.887 (0.01) & 0.875 (0.01)\\
concrete & 0.939 (0.027) & 0.918 (0.033) & 0.909 (0.031) & 0.879 (0.037) & 0.939 (0.027) & 0.891 (0.041) & 0.924 (0.032) & 0.921 (0.032) & 0.885 (0.033) & 0.815 (0.047) & 0.873 (0.039) & 0.873 (0.04) & 0.906 (0.037)\\
cycle & 0.916 (0.011) & 0.901 (0.011) & 0.912 (0.014) & 0.897 (0.014) & 0.916 (0.011) & 0.884 (0.012) & 0.893 (0.013) & 0.888 (0.013) & 0.852 (0.014) & 0.843 (0.014) & 0.858 (0.015) & 0.878 (0.014) & 0.863 (0.014)\\
electric & 0.898 (0.014) & 0.884 (0.013) & 0.904 (0.012) & 0.901 (0.012) & 0.898 (0.014) & 0.897 (0.012) & 0.897 (0.012) & 0.902 (0.011) & 0.911 (0.011) & 0.904 (0.012) & 0.897 (0.011) & 0.9 (0.01) & 0.914 (0.012)\\
homes & 0.875 (0.009) & 0.919 (0.005) & 0.899 (0.009) & 0.89 (0.008) & 0.875 (0.009) & 0.918 (0.007) & 0.911 (0.008) & 0.908 (0.007) & 0.892 (0.008) & 0.898 (0.007) & 0.89 (0.008) & 0.901 (0.007) & 0.903 (0.008)\\
meps19 & 0.889 (0.009) & 0.899 (0.008) & 0.903 (0.009) & 0.904 (0.008) & 0.889 (0.009) & 0.901 (0.009) & 0.904 (0.009) & 0.908 (0.007) & 0.894 (0.009) & 0.89 (0.01) & 0.897 (0.008) & 0.921 (0.015) & 0.894 (0.01)\\
news & 0.858 (0.005) & 0.914 (0.005) & 0.947 (0.003) & 0.947 (0.003) & 0.858 (0.005) & 0.911 (0.005) & 0.912 (0.005) & 0.914 (0.004) & 0.885 (0.005) & 0.899 (0.005) & 0.893 (0.005) & 0.901 (0.004) & 0.904 (0.005)\\
protein & 0.905 (0.005) & 0.902 (0.005) & 0.898 (0.006) & 0.896 (0.005) & 0.905 (0.005) & 0.902 (0.005) & 0.899 (0.006) & 0.898 (0.006) & 0.887 (0.006) & 0.886 (0.006) & 0.886 (0.005) & 0.89 (0.005) & 0.893 (0.007)\\
superconductivity & 0.864 (0.009) & 0.9 (0.008) & 0.924 (0.007) & 0.949 (0.007) & 0.864 (0.009) & 0.913 (0.01) & 0.902 (0.009) & 0.912 (0.008) & 0.874 (0.01) & 0.889 (0.009) & 0.871 (0.009) & 0.88 (0.009) & 0.88 (0.01)\\
winered & 0.89 (0.029) & 0.915 (0.03) & 0.89 (0.032) & 0.887 (0.032) & 0.89 (0.029) & 0.915 (0.027) & 0.91 (0.029) & 0.917 (0.027) & 0.808 (0.039) & 0.775 (0.045) & 0.854 (0.041) & 0.848 (0.043) & 0.854 (0.039)\\
winewhite & 0.876 (0.062) & 0.912 (0.011) & 0.893 (0.014) & 0.884 (0.014) & 0.876 (0.062) & 0.909 (0.012) & 0.897 (0.011) & 0.898 (0.012) & 0.861 (0.018) & 0.848 (0.02) & 0.881 (0.016) & 0.875 (0.014) & 0.877 (0.016)\\
\bottomrule\end{tabular}

Outlier/inlier ratio:

In [ ]:
output_ratio = pd.read_pickle(folder_path + "/result_ratio_outlier.pkl")
output_ratio

,Dataset,credo_GP,credo_QNN,credo_BART_adap,credo_BART_fixed,credo_GP_fixed,credo_QNN_fixed,credo_QNN_ens,credo_QNN_ens_fixed,cqr,cqrr,uacqrs,uacqrp,EPIC
0,airfoil,0.868 (0.042),0.918 (0.034),0.891 (0.031),0.884 (0.038),0.868 (0.042),0.909 (0.036),0.91 (0.033),0.902 (0.03),0.86 (0.055),0.85 (0.052),0.907 (0.039),0.903 (0.034),0.9 (0.046)
1,bike,0.916 (0.009),0.895 (0.013),0.918 (0.009),0.896 (0.011),0.916 (0.009),0.891 (0.013),0.893 (0.01),0.882 (0.011),0.873 (0.009),0.86 (0.01),0.881 (0.011),0.887 (0.01),0.875 (0.01)
2,concrete,0.939 (0.027),0.918 (0.033),0.909 (0.031),0.879 (0.037),0.939 (0.027),0.891 (0.041),0.924 (0.032),0.921 (0.032),0.885 (0.033),0.815 (0.047),0.873 (0.039),0.873 (0.04),0.906 (0.037)
3,cycle,0.916 (0.011),0.901 (0.011),0.912 (0.014),0.897 (0.014),0.916 (0.011),0.884 (0.012),0.893 (0.013),0.888 (0.013),0.852 (0.014),0.843 (0.014),0.858 (0.015),0.878 (0.014),0.863 (0.014)
4,electric,0.898 (0.014),0.884 (0.013),0.904 (0.012),0.901 (0.012),0.898 (0.014),0.897 (0.012),0.897 (0.012),0.902 (0.011),0.911 (0.011),0.904 (0.012),0.897 (0.011),0.9 (0.01),0.914 (0.012)
5,homes,0.875 (0.009),0.919 (0.005),0.899 (0.009),0.89 (0.008),0.875 (0.009),0.918 (0.007),0.911 (0.008),0.908 (0.007),0.892 (0.008),0.898 (0.007),0.89 (0.008),0.901 (0.007),0.903 (0.008)
6,meps19,0.889 (0.009),0.899 (0.008),0.903 (0.009),0.904 (0.008),0.889 (0.009),0.901 (0.009),0.904 (0.009),0.908 (0.007),0.894 (0.009),0.89 (0.01),0.897 (0.008),0.921 (0.015),0.894 (0.01)
7,news,0.858 (0.005),0.914 (0.005),0.947 (0.003),0.947 (0.003),0.858 (0.005),0.911 (0.005),0.912 (0.005),0.914 (0.004),0.885 (0.005),0.899 (0.005),0.893 (0.005),0.901 (0.004),0.904 (0.005)
8,protein,0.905 (0.005),0.902 (0.005),0.898 (0.006),0.896 (0.005),0.905 (0.005),0.902 (0.005),0.899 (0.006),0.898 (0.006),0.887 (0.006),0.886 (0.006),0.886 (0.005),0.89 (0.005),0.893 (0.007)
9,superconductivity,0.864 (0.009),0.9 (0.008),0.924 (0.007),0.949 (0.007),0.864 (0.009),0.913 (0.01),0.902 (0.009),0.912 (0.008),0.874 (0.01),0.889 (0.009),0.871 (0.009),0.88 (0.009),0.88 (0.01)
10,winered,0.89 (0.029),0.915 (0.03),0.89 (0.032),0.887 (0.032),0.89 (0.029),0.915 (0.027),0.91 (0.029),0.917 (0.027),0.808 (0.039),0.775 (0.045),0.854 (0.041),0.848 (0.043),0.854 (0.039)
11,winewhite,0.876 (0.062),0.912 (0.011),0.893 (0.014),0.884 (0.014),0.876 (0.062),0.909 (0.012),0.897 (0.011),0.898 (0.012),0.861 (0.018),0.848 (0.02),0.881 (0.016),0.875 (0.014),0.877 (0.016)

In [ ]:
custom_table_generator(output_ratio)

\begin{tabular}{lccccccccccccc}\toprule
Dataset & credo_GP & credo_QNN & credo_BART_adap & credo_BART_fixed & credo_GP_fixed & credo_QNN_fixed & credo_QNN_ens & credo_QNN_ens_fixed & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
airfoil & 0.868 (0.042) & 0.918 (0.034) & 0.891 (0.031) & 0.884 (0.038) & 0.868 (0.042) & 0.909 (0.036) & 0.91 (0.033) & 0.902 (0.03) & 0.86 (0.055) & 0.85 (0.052) & 0.907 (0.039) & 0.903 (0.034) & 0.9 (0.046)\\
bike & 0.916 (0.009) & 0.895 (0.013) & 0.918 (0.009) & 0.896 (0.011) & 0.916 (0.009) & 0.891 (0.013) & 0.893 (0.01) & 0.882 (0.011) & 0.873 (0.009) & 0.86 (0.01) & 0.881 (0.011) & 0.887 (0.01) & 0.875 (0.01)\\
concrete & 0.939 (0.027) & 0.918 (0.033) & 0.909 (0.031) & 0.879 (0.037) & 0.939 (0.027) & 0.891 (0.041) & 0.924 (0.032) & 0.921 (0.032) & 0.885 (0.033) & 0.815 (0.047) & 0.873 (0.039) & 0.873 (0.04) & 0.906 (0.037)\\
cycle & 0.916 (0.011) & 0.901 (0.011) & 0.912 (0.014) & 0.897 (0.014) & 0.916 (0.011) & 0.884 (0.012) & 0.893 (0.013) & 0.888 (0.013) & 0.852 (0.014) & 0.843 (0.014) & 0.858 (0.015) & 0.878 (0.014) & 0.863 (0.014)\\
electric & 0.898 (0.014) & 0.884 (0.013) & 0.904 (0.012) & 0.901 (0.012) & 0.898 (0.014) & 0.897 (0.012) & 0.897 (0.012) & 0.902 (0.011) & 0.911 (0.011) & 0.904 (0.012) & 0.897 (0.011) & 0.9 (0.01) & 0.914 (0.012)\\
homes & 0.875 (0.009) & 0.919 (0.005) & 0.899 (0.009) & 0.89 (0.008) & 0.875 (0.009) & 0.918 (0.007) & 0.911 (0.008) & 0.908 (0.007) & 0.892 (0.008) & 0.898 (0.007) & 0.89 (0.008) & 0.901 (0.007) & 0.903 (0.008)\\
meps19 & 0.889 (0.009) & 0.899 (0.008) & 0.903 (0.009) & 0.904 (0.008) & 0.889 (0.009) & 0.901 (0.009) & 0.904 (0.009) & 0.908 (0.007) & 0.894 (0.009) & 0.89 (0.01) & 0.897 (0.008) & 0.921 (0.015) & 0.894 (0.01)\\
news & 0.858 (0.005) & 0.914 (0.005) & 0.947 (0.003) & 0.947 (0.003) & 0.858 (0.005) & 0.911 (0.005) & 0.912 (0.005) & 0.914 (0.004) & 0.885 (0.005) & 0.899 (0.005) & 0.893 (0.005) & 0.901 (0.004) & 0.904 (0.005)\\
protein & 0.905 (0.005) & 0.902 (0.005) & 0.898 (0.006) & 0.896 (0.005) & 0.905 (0.005) & 0.902 (0.005) & 0.899 (0.006) & 0.898 (0.006) & 0.887 (0.006) & 0.886 (0.006) & 0.886 (0.005) & 0.89 (0.005) & 0.893 (0.007)\\
superconductivity & 0.864 (0.009) & 0.9 (0.008) & 0.924 (0.007) & 0.949 (0.007) & 0.864 (0.009) & 0.913 (0.01) & 0.902 (0.009) & 0.912 (0.008) & 0.874 (0.01) & 0.889 (0.009) & 0.871 (0.009) & 0.88 (0.009) & 0.88 (0.01)\\
winered & 0.89 (0.029) & 0.915 (0.03) & 0.89 (0.032) & 0.887 (0.032) & 0.89 (0.029) & 0.915 (0.027) & 0.91 (0.029) & 0.917 (0.027) & 0.808 (0.039) & 0.775 (0.045) & 0.854 (0.041) & 0.848 (0.043) & 0.854 (0.039)\\
winewhite & 0.876 (0.062) & 0.912 (0.011) & 0.893 (0.014) & 0.884 (0.014) & 0.876 (0.062) & 0.909 (0.012) & 0.897 (0.011) & 0.898 (0.012) & 0.861 (0.018) & 0.848 (0.02) & 0.881 (0.016) & 0.875 (0.014) & 0.877 (0.016)\\
\bottomrule\end{tabular}

AISL per outlier:

In [ ]:
output_aisl_out = pd.read_pickle(folder_path + "/result_aisl_outlier.pkl")
output_aisl_out

,Dataset,credo_GP,credo_QNN,credo_BART_adap,credo_BART_fixed,credo_GP_fixed,credo_QNN_fixed,credo_QNN_ens,credo_QNN_ens_fixed,cqr,cqrr,uacqrs,uacqrp,EPIC
0,airfoil,14.878 (2.428),14.551 (1.607),16.966 (2.335),17.544 (2.343),14.878 (2.428),14.459 (1.504),14.341 (1.767),14.637 (1.746),13.161 (1.811),20.485 (2.898),15.465 (1.558),17.477 (1.648),12.147 (1.559)
1,bike,575.538 (24.669),226.406 (10.0),444.712 (23.681),440.658 (21.134),575.538 (24.669),275.557 (8.497),209.87 (7.942),222.006 (7.313),198.612 (9.844),203.95 (9.337),201.438 (8.521),222.689 (9.107),195.622 (9.449)
2,concrete,29.219 (2.641),34.145 (3.752),29.743 (3.048),29.272 (3.077),29.219 (2.641),33.59 (3.573),32.216 (3.305),31.991 (3.009),31.288 (5.557),48.26 (9.166),43.888 (5.009),47.205 (4.976),30.703 (4.976)
3,cycle,19.108 (1.229),19.65 (1.127),19.262 (1.165),18.974 (1.229),19.108 (1.229),19.922 (1.176),18.578 (1.225),18.623 (1.241),16.903 (1.319),17.217 (1.356),17.157 (1.313),17.685 (1.203),16.768 (1.275)
4,electric,0.047 (0.002),0.036 (0.001),0.063 (0.002),0.064 (0.002),0.047 (0.002),0.037 (0.001),0.034 (0.001),0.035 (0.002),0.043 (0.002),0.046 (0.002),0.055 (0.002),0.061 (0.002),0.042 (0.002)
5,homes,974937.613 (87067.007),602289.666 (27926.552),940137.281 (77027.789),983030.847 (81442.616),974937.613 (87067.007),623452.738 (28339.546),529629.359 (25776.777),534708.766 (25805.109),633689.511 (59252.179),627423.194 (56254.221),628954.505 (56371.007),624232.151 (52843.208),595260.518 (43748.535)
6,meps19,115.287 (17.491),70.46 (10.381),96.766 (11.681),100.135 (11.367),115.287 (17.491),72.487 (10.177),68.976 (10.467),69.733 (10.337),78.314 (12.993),77.742 (12.886),73.903 (11.676),77.071 (11.925),76.461 (12.774)
7,news,38103.472 (3332.333),36317.689 (2801.249),46562.118 (2760.132),48889.582 (2762.343),38103.472 (3332.333),36625.509 (2693.781),34639.484 (2805.123),34698.794 (2765.012),33351.412 (3163.087),33375.614 (3162.385),32954.918 (3119.65),32688.753 (3134.214),33893.571 (3092.292)
8,protein,19.512 (0.246),15.756 (0.186),19.982 (0.258),20.102 (0.291),19.512 (0.246),16.161 (0.139),15.153 (0.199),15.286 (0.189),15.63 (0.273),15.633 (0.274),15.706 (0.234),16.045 (0.194),15.599 (0.244)
9,superconductivity,81.786 (2.798),54.751 (1.926),71.052 (2.036),75.865 (1.866),81.786 (2.798),59.419 (1.7),54.062 (2.049),54.993 (1.758),55.574 (2.033),55.422 (1.975),56.139 (1.908),58.497 (1.905),55.317 (1.897)
10,winered,3.053 (0.32),3.35 (0.285),3.133 (0.329),3.133 (0.359),3.053 (0.32),3.324 (0.255),3.25 (0.311),3.218 (0.303),4.059 (0.605),5.065 (0.773),3.303 (0.472),3.298 (0.467),3.58 (0.539)
11,winewhite,3.195 (0.24),3.498 (0.236),3.553 (0.242),3.616 (0.256),3.195 (0.24),3.577 (0.221),3.425 (0.213),3.448 (0.213),3.74 (0.273),3.904 (0.292),3.593 (0.243),3.762 (0.254),3.519 (0.221)

In [ ]:
custom_table_generator(output_aisl_out)

\begin{tabular}{lccccccccccccc}\toprule
Dataset & credo_GP & credo_QNN & credo_BART_adap & credo_BART_fixed & credo_GP_fixed & credo_QNN_fixed & credo_QNN_ens & credo_QNN_ens_fixed & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
airfoil & 14.878 (2.428) & 14.551 (1.607) & 16.966 (2.335) & 17.544 (2.343) & 14.878 (2.428) & 14.459 (1.504) & 14.341 (1.767) & 14.637 (1.746) & 13.161 (1.811) & 20.485 (2.898) & 15.465 (1.558) & 17.477 (1.648) & 12.147 (1.559)\\
bike & 575.538 (24.669) & 226.406 (10.0) & 444.712 (23.681) & 440.658 (21.134) & 575.538 (24.669) & 275.557 (8.497) & 209.87 (7.942) & 222.006 (7.313) & 198.612 (9.844) & 203.95 (9.337) & 201.438 (8.521) & 222.689 (9.107) & 195.622 (9.449)\\
concrete & 29.219 (2.641) & 34.145 (3.752) & 29.743 (3.048) & 29.272 (3.077) & 29.219 (2.641) & 33.59 (3.573) & 32.216 (3.305) & 31.991 (3.009) & 31.288 (5.557) & 48.26 (9.166) & 43.888 (5.009) & 47.205 (4.976) & 30.703 (4.976)\\
cycle & 19.108 (1.229) & 19.65 (1.127) & 19.262 (1.165) & 18.974 (1.229) & 19.108 (1.229) & 19.922 (1.176) & 18.578 (1.225) & 18.623 (1.241) & 16.903 (1.319) & 17.217 (1.356) & 17.157 (1.313) & 17.685 (1.203) & 16.768 (1.275)\\
electric & 0.047 (0.002) & 0.036 (0.001) & 0.063 (0.002) & 0.064 (0.002) & 0.047 (0.002) & 0.037 (0.001) & 0.034 (0.001) & 0.035 (0.002) & 0.043 (0.002) & 0.046 (0.002) & 0.055 (0.002) & 0.061 (0.002) & 0.042 (0.002)\\
homes & 974937.613 (87067.007) & 602289.666 (27926.552) & 940137.281 (77027.789) & 983030.847 (81442.616) & 974937.613 (87067.007) & 623452.738 (28339.546) & 529629.359 (25776.777) & 534708.766 (25805.109) & 633689.511 (59252.179) & 627423.194 (56254.221) & 628954.505 (56371.007) & 624232.151 (52843.208) & 595260.518 (43748.535)\\
meps19 & 115.287 (17.491) & 70.46 (10.381) & 96.766 (11.681) & 100.135 (11.367) & 115.287 (17.491) & 72.487 (10.177) & 68.976 (10.467) & 69.733 (10.337) & 78.314 (12.993) & 77.742 (12.886) & 73.903 (11.676) & 77.071 (11.925) & 76.461 (12.774)\\
news & 38103.472 (3332.333) & 36317.689 (2801.249) & 46562.118 (2760.132) & 48889.582 (2762.343) & 38103.472 (3332.333) & 36625.509 (2693.781) & 34639.484 (2805.123) & 34698.794 (2765.012) & 33351.412 (3163.087) & 33375.614 (3162.385) & 32954.918 (3119.65) & 32688.753 (3134.214) & 33893.571 (3092.292)\\
protein & 19.512 (0.246) & 15.756 (0.186) & 19.982 (0.258) & 20.102 (0.291) & 19.512 (0.246) & 16.161 (0.139) & 15.153 (0.199) & 15.286 (0.189) & 15.63 (0.273) & 15.633 (0.274) & 15.706 (0.234) & 16.045 (0.194) & 15.599 (0.244)\\
superconductivity & 81.786 (2.798) & 54.751 (1.926) & 71.052 (2.036) & 75.865 (1.866) & 81.786 (2.798) & 59.419 (1.7) & 54.062 (2.049) & 54.993 (1.758) & 55.574 (2.033) & 55.422 (1.975) & 56.139 (1.908) & 58.497 (1.905) & 55.317 (1.897)\\
winered & 3.053 (0.32) & 3.35 (0.285) & 3.133 (0.329) & 3.133 (0.359) & 3.053 (0.32) & 3.324 (0.255) & 3.25 (0.311) & 3.218 (0.303) & 4.059 (0.605) & 5.065 (0.773) & 3.303 (0.472) & 3.298 (0.467) & 3.58 (0.539)\\
winewhite & 3.195 (0.24) & 3.498 (0.236) & 3.553 (0.242) & 3.616 (0.256) & 3.195 (0.24) & 3.577 (0.221) & 3.425 (0.213) & 3.448 (0.213) & 3.74 (0.273) & 3.904 (0.292) & 3.593 (0.243) & 3.762 (0.254) & 3.519 (0.221)\\
\bottomrule\end{tabular}