# Printing and obtaining all results:

In [15]:
import os
import pandas as pd

original_path = os.getcwd()

def custom_table_generator(result):
    metrics = list(result.columns)[1:]

    print(f"\\begin{{tabular}}{{l{'c' * len(metrics)}}}\\toprule")
    print("Dataset & " + " & ".join(metrics) + "\\\\\\midrule")
    for _, row in result.iterrows():
        values = [row["Dataset"]]
        for metric in result.columns[1:]:
            value = row[metric]
            if pd.isna(value):
                values.append("-")
            else:
                values.append(f"{value}")
        print(" & ".join(values) + "\\\\")
    print("\\bottomrule\\end{tabular}")

Getting results:

In [16]:
folder_path = os.path.dirname(original_path) + "/results/final_tables/"

Marginal coverage:

In [17]:
output_cover = pd.read_pickle(folder_path + "/result_cover.pkl")
output_cover

,Dataset,credo_QNN,credo_QNN_adaptive,cqr,cqrr,uacqrs,uacqrp,EPIC
0,airfoil,0.903 (0.008),0.906 (0.009),0.905 (0.009),0.892 (0.008),0.904 (0.009),0.904 (0.011),0.913 (0.011)
1,concrete,0.907 (0.01),0.903 (0.01),0.895 (0.01),0.891 (0.01),0.895 (0.008),0.898 (0.008),0.898 (0.016)
2,cycle,0.898 (0.003),0.898 (0.003),0.895 (0.003),0.895 (0.003),0.895 (0.004),0.898 (0.003),0.895 (0.005)
3,electric,0.896 (0.003),0.899 (0.003),0.902 (0.003),0.899 (0.003),0.9 (0.003),0.9 (0.004),0.904 (0.004)
4,homes,0.902 (0.002),0.903 (0.002),0.904 (0.002),0.904 (0.002),0.903 (0.002),0.904 (0.002),0.9 (0.003)
5,meps19,0.899 (0.002),0.9 (0.003),0.899 (0.002),0.895 (0.002),0.901 (0.002),0.923 (0.011),0.9 (0.004)
6,protein,0.9 (0.001),0.901 (0.002),0.899 (0.001),0.899 (0.001),0.899 (0.001),0.9 (0.002),0.896 (0.004)
7,star,0.902 (0.007),0.902 (0.006),0.903 (0.007),0.897 (0.008),0.898 (0.005),0.897 (0.005),0.907 (0.01)
8,superconductivity,0.902 (0.002),0.902 (0.002),0.901 (0.003),0.901 (0.003),0.901 (0.003),0.902 (0.002),0.902 (0.003)
9,WEC,0.898 (0.001),0.9 (0.001),0.899 (0.001),0.899 (0.002),0.899 (0.001),0.899 (0.002),0.896 (0.004)
10,winered,0.901 (0.01),0.904 (0.008),0.901 (0.009),0.899 (0.009),0.898 (0.008),0.899 (0.008),0.901 (0.013)
11,winewhite,0.901 (0.004),0.9 (0.005),0.905 (0.004),0.904 (0.004),0.903 (0.004),0.902 (0.004),0.902 (0.008)

In [18]:
custom_table_generator(output_cover)

\begin{tabular}{lccccccc}\toprule
Dataset & credo_QNN & credo_QNN_adaptive & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
airfoil & 0.903 (0.008) & 0.906 (0.009) & 0.905 (0.009) & 0.892 (0.008) & 0.904 (0.009) & 0.904 (0.011) & 0.913 (0.011)\\
concrete & 0.907 (0.01) & 0.903 (0.01) & 0.895 (0.01) & 0.891 (0.01) & 0.895 (0.008) & 0.898 (0.008) & 0.898 (0.016)\\
cycle & 0.898 (0.003) & 0.898 (0.003) & 0.895 (0.003) & 0.895 (0.003) & 0.895 (0.004) & 0.898 (0.003) & 0.895 (0.005)\\
electric & 0.896 (0.003) & 0.899 (0.003) & 0.902 (0.003) & 0.899 (0.003) & 0.9 (0.003) & 0.9 (0.004) & 0.904 (0.004)\\
homes & 0.902 (0.002) & 0.903 (0.002) & 0.904 (0.002) & 0.904 (0.002) & 0.903 (0.002) & 0.904 (0.002) & 0.9 (0.003)\\
meps19 & 0.899 (0.002) & 0.9 (0.003) & 0.899 (0.002) & 0.895 (0.002) & 0.901 (0.002) & 0.923 (0.011) & 0.9 (0.004)\\
protein & 0.9 (0.001) & 0.901 (0.002) & 0.899 (0.001) & 0.899 (0.001) & 0.899 (0.001) & 0.9 (0.002) & 0.896 (0.004)\\
star & 0.902 (0.007) & 0.902 (0.006) & 0.903 (0.007) & 0.897 (0.008) & 0.898 (0.005) & 0.897 (0.005) & 0.907 (0.01)\\
superconductivity & 0.902 (0.002) & 0.902 (0.002) & 0.901 (0.003) & 0.901 (0.003) & 0.901 (0.003) & 0.902 (0.002) & 0.902 (0.003)\\
WEC & 0.898 (0.001) & 0.9 (0.001) & 0.899 (0.001) & 0.899 (0.002) & 0.899 (0.001) & 0.899 (0.002) & 0.896 (0.004)\\
winered & 0.901 (0.01) & 0.904 (0.008) & 0.901 (0.009) & 0.899 (0.009) & 0.898 (0.008) & 0.899 (0.008) & 0.901 (0.013)\\
winewhite & 0.901 (0.004) & 0.9 (0.005) & 0.905 (0.004) & 0.904 (0.004) & 0.903 (0.004) & 0.902 (0.004) & 0.902 (0.008)\\
\bottomrule\end{tabular}

Average Interval Score Length:

In [19]:
output_aisl = pd.read_pickle(folder_path + "/result_aisl.pkl")
output_aisl

,Dataset,credo_QNN,credo_QNN_adaptive,cqr,cqrr,uacqrs,uacqrp,EPIC
0,airfoil,11.374 (0.349),11.252 (0.296),10.51 (0.255),13.678 (0.69),12.684 (0.455),14.742 (0.723),9.947 (0.238)
1,concrete,27.594 (0.745),26.493 (0.727),28.562 (0.923),35.485 (1.547),36.524 (1.415),40.944 (2.058),27.506 (0.818)
2,cycle,18.267 (0.194),17.649 (0.142),15.301 (0.164),15.389 (0.167),15.632 (0.164),16.301 (0.224),15.292 (0.167)
3,electric,0.037 (0.001),0.035 (0.001),0.044 (0.0),0.047 (0.0),0.054 (0.001),0.06 (0.001),0.043 (0.0)
4,homes,461856.806 (4623.344),432057.703 (3679.218),428142.976 (5111.253),425948.712 (4770.94),432517.736 (4954.39),443312.873 (5678.878),417177.441 (4667.94)
5,meps19,61.771 (1.402),57.205 (1.503),58.824 (2.093),58.594 (2.073),56.453 (1.846),58.815 (2.035),57.906 (2.036)
6,protein,15.224 (0.054),14.744 (0.057),15.171 (0.048),15.169 (0.048),15.325 (0.045),15.769 (0.051),15.12 (0.047)
7,star,992.358 (14.281),975.232 (10.954),1007.843 (16.458),1133.092 (30.298),956.197 (13.802),967.46 (16.717),1005.743 (17.407)
8,superconductivity,49.757 (0.537),44.169 (0.507),43.762 (0.354),43.787 (0.341),45.263 (0.39),47.569 (0.361),43.671 (0.343)
9,WEC,96692.549 (753.445),86672.226 (646.515),126727.69 (1226.006),126726.717 (1225.998),126733.044 (1226.235),135309.892 (1168.906),122406.815 (1105.797)
10,winered,2.735 (0.052),2.661 (0.053),2.984 (0.069),3.139 (0.091),2.77 (0.059),2.817 (0.059),2.817 (0.058)
11,winewhite,3.005 (0.027),2.875 (0.032),2.958 (0.032),2.991 (0.034),2.923 (0.029),3.006 (0.032),2.892 (0.032)

In [20]:
custom_table_generator(output_aisl)

\begin{tabular}{lccccccc}\toprule
Dataset & credo_QNN & credo_QNN_adaptive & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
airfoil & 11.374 (0.349) & 11.252 (0.296) & 10.51 (0.255) & 13.678 (0.69) & 12.684 (0.455) & 14.742 (0.723) & 9.947 (0.238)\\
concrete & 27.594 (0.745) & 26.493 (0.727) & 28.562 (0.923) & 35.485 (1.547) & 36.524 (1.415) & 40.944 (2.058) & 27.506 (0.818)\\
cycle & 18.267 (0.194) & 17.649 (0.142) & 15.301 (0.164) & 15.389 (0.167) & 15.632 (0.164) & 16.301 (0.224) & 15.292 (0.167)\\
electric & 0.037 (0.001) & 0.035 (0.001) & 0.044 (0.0) & 0.047 (0.0) & 0.054 (0.001) & 0.06 (0.001) & 0.043 (0.0)\\
homes & 461856.806 (4623.344) & 432057.703 (3679.218) & 428142.976 (5111.253) & 425948.712 (4770.94) & 432517.736 (4954.39) & 443312.873 (5678.878) & 417177.441 (4667.94)\\
meps19 & 61.771 (1.402) & 57.205 (1.503) & 58.824 (2.093) & 58.594 (2.073) & 56.453 (1.846) & 58.815 (2.035) & 57.906 (2.036)\\
protein & 15.224 (0.054) & 14.744 (0.057) & 15.171 (0.048) & 15.169 (0.048) & 15.325 (0.045) & 15.769 (0.051) & 15.12 (0.047)\\
star & 992.358 (14.281) & 975.232 (10.954) & 1007.843 (16.458) & 1133.092 (30.298) & 956.197 (13.802) & 967.46 (16.717) & 1005.743 (17.407)\\
superconductivity & 49.757 (0.537) & 44.169 (0.507) & 43.762 (0.354) & 43.787 (0.341) & 45.263 (0.39) & 47.569 (0.361) & 43.671 (0.343)\\
WEC & 96692.549 (753.445) & 86672.226 (646.515) & 126727.69 (1226.006) & 126726.717 (1225.998) & 126733.044 (1226.235) & 135309.892 (1168.906) & 122406.815 (1105.797)\\
winered & 2.735 (0.052) & 2.661 (0.053) & 2.984 (0.069) & 3.139 (0.091) & 2.77 (0.059) & 2.817 (0.059) & 2.817 (0.058)\\
winewhite & 3.005 (0.027) & 2.875 (0.032) & 2.958 (0.032) & 2.991 (0.034) & 2.923 (0.029) & 3.006 (0.032) & 2.892 (0.032)\\
\bottomrule\end{tabular}

Interval length:

In [21]:
output_il = pd.read_pickle(folder_path + "/result_il.pkl")
output_il

,Dataset,credo_QNN,credo_QNN_adaptive,cqr,cqrr,uacqrs,uacqrp,EPIC
0,airfoil,9.3 (0.2),9.116 (0.223),7.88 (0.222),9.674 (0.483),10.426 (0.495),12.617 (0.772),7.966 (0.241)
1,concrete,21.741 (0.484),20.555 (0.611),19.728 (0.487),24.798 (1.206),28.552 (1.435),33.514 (2.174),19.981 (0.935)
2,cycle,14.22 (0.162),13.726 (0.129),11.563 (0.063),11.64 (0.069),12.06 (0.107),12.779 (0.229),11.552 (0.116)
3,electric,0.03 (0.001),0.028 (0.001),0.034 (0.0),0.037 (0.0),0.045 (0.001),0.051 (0.001),0.035 (0.0)
4,homes,390121.577 (4795.877),354499.855 (2918.211),294888.77 (1749.982),306433.944 (1995.245),305396.488 (2276.398),328254.429 (3049.844),307882.838 (3757.623)
5,meps19,47.917 (0.968),39.643 (0.866),23.057 (0.334),23.342 (0.331),31.532 (0.403),33.978 (0.706),24.683 (0.544)
6,protein,14.097 (0.062),13.327 (0.055),12.992 (0.026),13.004 (0.026),13.442 (0.036),14.091 (0.056),13.021 (0.044)
7,star,821.13 (11.047),810.606 (9.434),811.157 (10.514),876.054 (22.656),791.453 (9.329),801.768 (14.219),823.418 (22.273)
8,superconductivity,46.176 (0.524),38.728 (0.454),35.852 (0.181),36.759 (0.167),38.498 (0.367),41.368 (0.298),36.113 (0.286)
9,WEC,78809.095 (827.777),66475.151 (606.267),97807.533 (904.517),97835.574 (900.53),97821.872 (904.7),104541.963 (923.528),90987.449 (1237.958)
10,winered,2.177 (0.037),2.036 (0.038),1.961 (0.074),1.997 (0.085),1.951 (0.035),1.956 (0.055),1.948 (0.095)
11,winewhite,2.454 (0.027),2.276 (0.016),2.061 (0.025),2.077 (0.028),2.188 (0.018),2.202 (0.016),2.072 (0.042)

In [22]:
custom_table_generator(output_il)

\begin{tabular}{lccccccc}\toprule
Dataset & credo_QNN & credo_QNN_adaptive & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
airfoil & 9.3 (0.2) & 9.116 (0.223) & 7.88 (0.222) & 9.674 (0.483) & 10.426 (0.495) & 12.617 (0.772) & 7.966 (0.241)\\
concrete & 21.741 (0.484) & 20.555 (0.611) & 19.728 (0.487) & 24.798 (1.206) & 28.552 (1.435) & 33.514 (2.174) & 19.981 (0.935)\\
cycle & 14.22 (0.162) & 13.726 (0.129) & 11.563 (0.063) & 11.64 (0.069) & 12.06 (0.107) & 12.779 (0.229) & 11.552 (0.116)\\
electric & 0.03 (0.001) & 0.028 (0.001) & 0.034 (0.0) & 0.037 (0.0) & 0.045 (0.001) & 0.051 (0.001) & 0.035 (0.0)\\
homes & 390121.577 (4795.877) & 354499.855 (2918.211) & 294888.77 (1749.982) & 306433.944 (1995.245) & 305396.488 (2276.398) & 328254.429 (3049.844) & 307882.838 (3757.623)\\
meps19 & 47.917 (0.968) & 39.643 (0.866) & 23.057 (0.334) & 23.342 (0.331) & 31.532 (0.403) & 33.978 (0.706) & 24.683 (0.544)\\
protein & 14.097 (0.062) & 13.327 (0.055) & 12.992 (0.026) & 13.004 (0.026) & 13.442 (0.036) & 14.091 (0.056) & 13.021 (0.044)\\
star & 821.13 (11.047) & 810.606 (9.434) & 811.157 (10.514) & 876.054 (22.656) & 791.453 (9.329) & 801.768 (14.219) & 823.418 (22.273)\\
superconductivity & 46.176 (0.524) & 38.728 (0.454) & 35.852 (0.181) & 36.759 (0.167) & 38.498 (0.367) & 41.368 (0.298) & 36.113 (0.286)\\
WEC & 78809.095 (827.777) & 66475.151 (606.267) & 97807.533 (904.517) & 97835.574 (900.53) & 97821.872 (904.7) & 104541.963 (923.528) & 90987.449 (1237.958)\\
winered & 2.177 (0.037) & 2.036 (0.038) & 1.961 (0.074) & 1.997 (0.085) & 1.951 (0.035) & 1.956 (0.055) & 1.948 (0.095)\\
winewhite & 2.454 (0.027) & 2.276 (0.016) & 2.061 (0.025) & 2.077 (0.028) & 2.188 (0.018) & 2.202 (0.016) & 2.072 (0.042)\\
\bottomrule\end{tabular}

Pearson Correlation:

In [23]:
output_pcor = pd.read_pickle(folder_path + "/result_pcorr.pkl")
output_pcor

,Dataset,credo_QNN,credo_QNN_adaptive,cqr,cqrr,uacqrs,uacqrp,EPIC
0,airfoil,0.112 (0.024),0.074 (0.021),0.226 (0.03),0.454 (0.019),0.063 (0.02),0.053 (0.019),0.13 (0.021)
1,concrete,0.112 (0.026),0.077 (0.019),0.173 (0.037),0.426 (0.027),0.09 (0.028),0.076 (0.022),0.112 (0.032)
2,cycle,0.164 (0.01),0.109 (0.009),0.055 (0.009),0.121 (0.01),0.036 (0.008),0.027 (0.007),0.049 (0.01)
3,electric,0.157 (0.02),0.108 (0.019),0.082 (0.011),0.301 (0.012),0.045 (0.009),0.064 (0.011),0.1 (0.013)
4,homes,0.107 (0.004),0.082 (0.004),0.053 (0.009),0.018 (0.005),0.042 (0.009),0.026 (0.007),0.017 (0.005)
5,meps19,0.088 (0.01),0.065 (0.009),0.089 (0.008),0.019 (0.006),0.044 (0.008),0.058 (0.021),0.019 (0.006)
6,protein,0.074 (0.011),0.029 (0.009),0.028 (0.004),0.013 (0.004),0.046 (0.005),0.047 (0.005),0.02 (0.005)
7,star,0.148 (0.016),0.128 (0.019),0.298 (0.025),0.47 (0.025),0.061 (0.015),0.047 (0.012),0.26 (0.027)
8,superconductivity,0.234 (0.006),0.15 (0.008),0.051 (0.01),0.053 (0.007),0.038 (0.008),0.024 (0.006),0.038 (0.009)
9,WEC,0.196 (0.004),0.14 (0.006),0.02 (0.005),0.016 (0.005),0.019 (0.005),0.028 (0.005),0.076 (0.006)
10,winered,0.121 (0.023),0.089 (0.017),0.22 (0.028),0.284 (0.029),0.064 (0.017),0.1 (0.02),0.075 (0.02)
11,winewhite,0.152 (0.018),0.114 (0.018),0.097 (0.016),0.143 (0.02),0.025 (0.007),0.094 (0.015),0.036 (0.01)

In [24]:
custom_table_generator(output_pcor)

\begin{tabular}{lccccccc}\toprule
Dataset & credo_QNN & credo_QNN_adaptive & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
airfoil & 0.112 (0.024) & 0.074 (0.021) & 0.226 (0.03) & 0.454 (0.019) & 0.063 (0.02) & 0.053 (0.019) & 0.13 (0.021)\\
concrete & 0.112 (0.026) & 0.077 (0.019) & 0.173 (0.037) & 0.426 (0.027) & 0.09 (0.028) & 0.076 (0.022) & 0.112 (0.032)\\
cycle & 0.164 (0.01) & 0.109 (0.009) & 0.055 (0.009) & 0.121 (0.01) & 0.036 (0.008) & 0.027 (0.007) & 0.049 (0.01)\\
electric & 0.157 (0.02) & 0.108 (0.019) & 0.082 (0.011) & 0.301 (0.012) & 0.045 (0.009) & 0.064 (0.011) & 0.1 (0.013)\\
homes & 0.107 (0.004) & 0.082 (0.004) & 0.053 (0.009) & 0.018 (0.005) & 0.042 (0.009) & 0.026 (0.007) & 0.017 (0.005)\\
meps19 & 0.088 (0.01) & 0.065 (0.009) & 0.089 (0.008) & 0.019 (0.006) & 0.044 (0.008) & 0.058 (0.021) & 0.019 (0.006)\\
protein & 0.074 (0.011) & 0.029 (0.009) & 0.028 (0.004) & 0.013 (0.004) & 0.046 (0.005) & 0.047 (0.005) & 0.02 (0.005)\\
star & 0.148 (0.016) & 0.128 (0.019) & 0.298 (0.025) & 0.47 (0.025) & 0.061 (0.015) & 0.047 (0.012) & 0.26 (0.027)\\
superconductivity & 0.234 (0.006) & 0.15 (0.008) & 0.051 (0.01) & 0.053 (0.007) & 0.038 (0.008) & 0.024 (0.006) & 0.038 (0.009)\\
WEC & 0.196 (0.004) & 0.14 (0.006) & 0.02 (0.005) & 0.016 (0.005) & 0.019 (0.005) & 0.028 (0.005) & 0.076 (0.006)\\
winered & 0.121 (0.023) & 0.089 (0.017) & 0.22 (0.028) & 0.284 (0.029) & 0.064 (0.017) & 0.1 (0.02) & 0.075 (0.02)\\
winewhite & 0.152 (0.018) & 0.114 (0.018) & 0.097 (0.016) & 0.143 (0.02) & 0.025 (0.007) & 0.094 (0.015) & 0.036 (0.01)\\
\bottomrule\end{tabular}

Outlier coverage:

In [25]:
output_cover = pd.read_pickle(folder_path + "/result_cover_outlier.pkl")
output_cover

,Dataset,credo_QNN,credo_QNN_adaptive,cqr,cqrr,uacqrs,uacqrp,EPIC
0,airfoil,0.898 (0.035),0.894 (0.033),0.872 (0.041),0.879 (0.046),0.907 (0.041),0.894 (0.039),0.912 (0.03)
1,concrete,0.918 (0.027),0.921 (0.033),0.867 (0.042),0.848 (0.045),0.875 (0.046),0.859 (0.04),0.87 (0.045)
2,cycle,0.889 (0.016),0.906 (0.011),0.852 (0.014),0.843 (0.014),0.858 (0.015),0.878 (0.014),0.862 (0.012)
3,electric,0.882 (0.011),0.89 (0.013),0.911 (0.011),0.904 (0.012),0.897 (0.011),0.9 (0.01),0.912 (0.012)
4,homes,0.92 (0.007),0.917 (0.007),0.892 (0.008),0.898 (0.007),0.89 (0.008),0.901 (0.007),0.901 (0.008)
5,meps19,0.902 (0.009),0.9 (0.009),0.894 (0.009),0.89 (0.01),0.897 (0.008),0.921 (0.015),0.891 (0.01)
6,protein,0.9 (0.006),0.901 (0.005),0.887 (0.006),0.886 (0.006),0.886 (0.005),0.89 (0.005),0.89 (0.006)
7,star,0.879 (0.024),0.871 (0.021),0.785 (0.036),0.744 (0.041),0.852 (0.026),0.854 (0.023),0.803 (0.032)
8,superconductivity,0.918 (0.008),0.909 (0.009),0.874 (0.01),0.889 (0.009),0.871 (0.009),0.88 (0.009),0.878 (0.009)
9,WEC,0.863 (0.009),0.844 (0.01),0.849 (0.01),0.849 (0.01),0.849 (0.01),0.853 (0.009),0.841 (0.01)
10,winered,0.908 (0.029),0.9 (0.03),0.819 (0.043),0.798 (0.044),0.835 (0.045),0.838 (0.045),0.833 (0.042)
11,winewhite,0.902 (0.014),0.89 (0.017),0.856 (0.02),0.847 (0.02),0.894 (0.016),0.879 (0.014),0.879 (0.018)

In [26]:
custom_table_generator(output_cover)

\begin{tabular}{lccccccc}\toprule
Dataset & credo_QNN & credo_QNN_adaptive & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
airfoil & 0.898 (0.035) & 0.894 (0.033) & 0.872 (0.041) & 0.879 (0.046) & 0.907 (0.041) & 0.894 (0.039) & 0.912 (0.03)\\
concrete & 0.918 (0.027) & 0.921 (0.033) & 0.867 (0.042) & 0.848 (0.045) & 0.875 (0.046) & 0.859 (0.04) & 0.87 (0.045)\\
cycle & 0.889 (0.016) & 0.906 (0.011) & 0.852 (0.014) & 0.843 (0.014) & 0.858 (0.015) & 0.878 (0.014) & 0.862 (0.012)\\
electric & 0.882 (0.011) & 0.89 (0.013) & 0.911 (0.011) & 0.904 (0.012) & 0.897 (0.011) & 0.9 (0.01) & 0.912 (0.012)\\
homes & 0.92 (0.007) & 0.917 (0.007) & 0.892 (0.008) & 0.898 (0.007) & 0.89 (0.008) & 0.901 (0.007) & 0.901 (0.008)\\
meps19 & 0.902 (0.009) & 0.9 (0.009) & 0.894 (0.009) & 0.89 (0.01) & 0.897 (0.008) & 0.921 (0.015) & 0.891 (0.01)\\
protein & 0.9 (0.006) & 0.901 (0.005) & 0.887 (0.006) & 0.886 (0.006) & 0.886 (0.005) & 0.89 (0.005) & 0.89 (0.006)\\
star & 0.879 (0.024) & 0.871 (0.021) & 0.785 (0.036) & 0.744 (0.041) & 0.852 (0.026) & 0.854 (0.023) & 0.803 (0.032)\\
superconductivity & 0.918 (0.008) & 0.909 (0.009) & 0.874 (0.01) & 0.889 (0.009) & 0.871 (0.009) & 0.88 (0.009) & 0.878 (0.009)\\
WEC & 0.863 (0.009) & 0.844 (0.01) & 0.849 (0.01) & 0.849 (0.01) & 0.849 (0.01) & 0.853 (0.009) & 0.841 (0.01)\\
winered & 0.908 (0.029) & 0.9 (0.03) & 0.819 (0.043) & 0.798 (0.044) & 0.835 (0.045) & 0.838 (0.045) & 0.833 (0.042)\\
winewhite & 0.902 (0.014) & 0.89 (0.017) & 0.856 (0.02) & 0.847 (0.02) & 0.894 (0.016) & 0.879 (0.014) & 0.879 (0.018)\\
\bottomrule\end{tabular}

Outlier/inlier ratio:

In [27]:
output_ratio = pd.read_pickle(folder_path + "/result_ratio_outlier.pkl")
output_ratio

,Dataset,credo_QNN,credo_QNN_adaptive,cqr,cqrr,uacqrs,uacqrp,EPIC
0,airfoil,1.229 (0.098),1.205 (0.095),1.059 (0.071),1.092 (0.108),1.053 (0.036),1.071 (0.043),1.098 (0.066)
1,concrete,1.094 (0.065),1.149 (0.066),0.831 (0.045),0.732 (0.071),0.948 (0.023),0.996 (0.028),0.923 (0.054)
2,cycle,1.002 (0.022),1.048 (0.018),0.881 (0.017),0.867 (0.019),0.891 (0.016),0.952 (0.017),0.89 (0.017)
3,electric,0.955 (0.022),0.957 (0.021),1.001 (0.023),1.001 (0.03),1.008 (0.013),1.02 (0.011),0.995 (0.027)
4,homes,1.644 (0.077),1.637 (0.075),1.358 (0.04),1.402 (0.045),1.361 (0.042),1.442 (0.051),1.504 (0.056)
5,meps19,1.121 (0.068),1.114 (0.075),1.131 (0.059),1.137 (0.062),1.13 (0.054),1.111 (0.045),1.128 (0.062)
6,protein,1.024 (0.005),1.027 (0.006),0.991 (0.006),0.991 (0.006),0.994 (0.005),1.0 (0.005),1.003 (0.007)
7,star,0.992 (0.016),0.992 (0.014),0.904 (0.021),0.855 (0.033),1.004 (0.01),0.998 (0.007),0.914 (0.02)
8,superconductivity,1.099 (0.028),1.089 (0.028),1.143 (0.028),1.147 (0.029),1.124 (0.026),1.139 (0.026),1.146 (0.029)
9,WEC,1.248 (0.034),1.249 (0.033),1.16 (0.02),1.16 (0.02),1.16 (0.02),1.161 (0.018),1.213 (0.022)
10,winered,1.235 (0.055),1.253 (0.059),0.877 (0.031),0.832 (0.042),1.007 (0.022),1.013 (0.016),1.019 (0.047)
11,winewhite,1.113 (0.03),1.112 (0.027),0.955 (0.019),0.948 (0.022),1.03 (0.015),1.036 (0.012),1.024 (0.029)

In [28]:
custom_table_generator(output_ratio)

\begin{tabular}{lccccccc}\toprule
Dataset & credo_QNN & credo_QNN_adaptive & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
airfoil & 1.229 (0.098) & 1.205 (0.095) & 1.059 (0.071) & 1.092 (0.108) & 1.053 (0.036) & 1.071 (0.043) & 1.098 (0.066)\\
concrete & 1.094 (0.065) & 1.149 (0.066) & 0.831 (0.045) & 0.732 (0.071) & 0.948 (0.023) & 0.996 (0.028) & 0.923 (0.054)\\
cycle & 1.002 (0.022) & 1.048 (0.018) & 0.881 (0.017) & 0.867 (0.019) & 0.891 (0.016) & 0.952 (0.017) & 0.89 (0.017)\\
electric & 0.955 (0.022) & 0.957 (0.021) & 1.001 (0.023) & 1.001 (0.03) & 1.008 (0.013) & 1.02 (0.011) & 0.995 (0.027)\\
homes & 1.644 (0.077) & 1.637 (0.075) & 1.358 (0.04) & 1.402 (0.045) & 1.361 (0.042) & 1.442 (0.051) & 1.504 (0.056)\\
meps19 & 1.121 (0.068) & 1.114 (0.075) & 1.131 (0.059) & 1.137 (0.062) & 1.13 (0.054) & 1.111 (0.045) & 1.128 (0.062)\\
protein & 1.024 (0.005) & 1.027 (0.006) & 0.991 (0.006) & 0.991 (0.006) & 0.994 (0.005) & 1.0 (0.005) & 1.003 (0.007)\\
star & 0.992 (0.016) & 0.992 (0.014) & 0.904 (0.021) & 0.855 (0.033) & 1.004 (0.01) & 0.998 (0.007) & 0.914 (0.02)\\
superconductivity & 1.099 (0.028) & 1.089 (0.028) & 1.143 (0.028) & 1.147 (0.029) & 1.124 (0.026) & 1.139 (0.026) & 1.146 (0.029)\\
WEC & 1.248 (0.034) & 1.249 (0.033) & 1.16 (0.02) & 1.16 (0.02) & 1.16 (0.02) & 1.161 (0.018) & 1.213 (0.022)\\
winered & 1.235 (0.055) & 1.253 (0.059) & 0.877 (0.031) & 0.832 (0.042) & 1.007 (0.022) & 1.013 (0.016) & 1.019 (0.047)\\
winewhite & 1.113 (0.03) & 1.112 (0.027) & 0.955 (0.019) & 0.948 (0.022) & 1.03 (0.015) & 1.036 (0.012) & 1.024 (0.029)\\
\bottomrule\end{tabular}