# Printing and obtaining all results:

In [2]:
import os
import pandas as pd

original_path = os.getcwd()

def custom_table_generator(result):
    metrics = list(result.columns)[1:]

    print(f"\\begin{{tabular}}{{l{'c' * len(metrics)}}}\\toprule")
    print("Dataset & " + " & ".join(metrics) + "\\\\\\midrule")
    for _, row in result.iterrows():
        values = [row["Dataset"]]
        for metric in result.columns[1:]:
            value = row[metric]
            if pd.isna(value):
                values.append("-")
            else:
                values.append(f"{value}")
        print(" & ".join(values) + "\\\\")
    print("\\bottomrule\\end{tabular}")

Getting results:

In [ ]:
from pathlib import Path

project_root = Path.cwd()
if project_root.name == "comparisons":
    project_root = project_root.parent

folder_path = project_root / "results" / "final_tables"

Marginal coverage:

In [ ]:
output_cover = pd.read_pickle(folder_path / "result_cover.pkl")
output_cover

In [ ]:
custom_table_generator(output_cover)

Average Interval Score Length:

In [ ]:
output_aisl = pd.read_pickle(folder_path / "result_aisl.pkl")
output_aisl

In [ ]:
custom_table_generator(output_aisl)

Interval length:

In [ ]:
output_il = pd.read_pickle(folder_path / "result_qnn_interval_length.pkl")
output_il

In [ ]:
custom_table_generator(output_il)

Outlier coverage (LOF):

In [ ]:
output_cover = pd.read_pickle(folder_path / "result_cover_outlier.pkl")
output_cover

In [ ]:
custom_table_generator(output_cover)

Outlier/inlier ratio (LOF):

In [ ]:
output_ratio = pd.read_pickle(folder_path / "result_ratio_outlier.pkl")
output_ratio

In [ ]:
custom_table_generator(output_ratio)

## QNN results

In [3]:
from pathlib import Path
from IPython.display import Markdown, display

project_root = Path.cwd()
if project_root.name == "comparisons":
    project_root = project_root.parent

folder_path = project_root / "results" / "final_tables"
assert folder_path.exists(), f"Final tables folder not found: {folder_path}"

qnn_dataset_order = [
    "concrete", "airfoil", "winewhite", "star",
    "winered", "cycle", "electric", "meps19",
]

def order_qnn_datasets(table):
    available = [dataset for dataset in qnn_dataset_order if dataset in set(table["Dataset"])]
    return table.set_index("Dataset").loc[available].reset_index()

qnn_table_files = {
    "QNN SMIS": "result_qnn_smis.pkl",
    "QNN interval length": "result_qnn_interval_length.pkl",
    "QNN WSC": "result_qnn_wsc.pkl",
    "QNN scarcity worst coverage": "result_qnn_scarcity_worst_coverage.pkl",
    "QNN scarcity coverage - Q3": "result_qnn_scarcity_coverage_Q3.pkl",
    "QNN scarcity coverage - Q4": "result_qnn_scarcity_coverage_Q4.pkl",
}

qnn_tables = {}
for title, filename in qnn_table_files.items():
    qnn_tables[title] = order_qnn_datasets(pd.read_pickle(folder_path / filename))
    display(Markdown(f"### {title}"))
    display(qnn_tables[title])

### QNN SMIS

,Dataset,credo_QNN,credo_QNN_adaptive,cqr,cqrr,uacqrs,uacqrp,EPIC
0,concrete,27.259 (0.772),26.962 (0.802),26.819 (0.996),26.951 (1.026),26.602 (0.971),25.836 (0.79),26.41 (0.858)
1,airfoil,11.497 (0.333),11.329 (0.331),8.995 (0.31),9.004 (0.308),9.038 (0.309),8.915 (0.296),8.87 (0.278)
2,winewhite,3.002 (0.027),2.873 (0.029),2.959 (0.031),2.969 (0.03),2.958 (0.03),2.896 (0.033),2.966 (0.031)
3,star,995.35 (14.778),976.693 (15.42),994.844 (12.668),1017.103 (12.741),1015.037 (13.59),988.443 (14.273),1009.792 (12.929)
4,winered,2.722 (0.047),2.65 (0.055),2.713 (0.052),2.731 (0.054),2.708 (0.053),2.686 (0.053),2.743 (0.054)
5,cycle,18.413 (0.212),17.696 (0.16),15.97 (0.178),15.958 (0.18),15.976 (0.178),15.707 (0.165),15.955 (0.178)
6,electric,0.038 (0.0),0.038 (0.001),0.033 (0.0),0.033 (0.0),0.033 (0.0),0.032 (0.0),0.031 (0.0)
7,meps19,61.267 (1.242),57.698 (1.613),63.232 (2.256),63.278 (2.231),63.395 (2.375),68.899 (2.477),62.612 (2.174)

### QNN interval length

,Dataset,credo_QNN,credo_QNN_adaptive,cqr,cqrr,uacqrs,uacqrp,EPIC
0,concrete,21.55 (0.563),21.181 (0.486),18.91 (0.57),19.095 (0.61),18.835 (0.562),18.4 (0.516),19.067 (0.87)
1,airfoil,9.404 (0.254),9.114 (0.196),6.807 (0.194),6.783 (0.195),6.769 (0.201),6.463 (0.166),6.8 (0.301)
2,winewhite,2.496 (0.036),2.283 (0.02),2.218 (0.023),2.234 (0.025),2.233 (0.024),2.152 (0.021),2.24 (0.043)
3,star,827.402 (10.993),813.281 (9.247),810.629 (10.009),832.042 (11.528),829.841 (10.42),817.904 (10.641),837.018 (21.906)
4,winered,2.2 (0.038),2.026 (0.04),2.009 (0.034),2.039 (0.04),2.015 (0.036),1.994 (0.037),2.043 (0.08)
5,cycle,14.342 (0.145),13.827 (0.135),11.945 (0.093),11.93 (0.096),11.946 (0.095),11.857 (0.082),11.912 (0.168)
6,electric,0.031 (0.001),0.03 (0.001),0.024 (0.0),0.023 (0.0),0.024 (0.0),0.022 (0.0),0.023 (0.0)
7,meps19,47.414 (0.773),39.546 (0.746),29.487 (1.063),29.408 (1.156),29.327 (1.049),21.816 (0.335),30.321 (1.057)

### QNN WSC

,Dataset,credo_QNN,credo_QNN_adaptive,cqr,cqrr,uacqrs,uacqrp,EPIC
0,concrete,0.721 (0.025),0.741 (0.019),0.721 (0.021),0.721 (0.021),0.718 (0.022),0.724 (0.02),0.724 (0.024)
1,airfoil,0.689 (0.019),0.695 (0.02),0.699 (0.025),0.698 (0.025),0.691 (0.027),0.701 (0.025),0.715 (0.03)
2,winewhite,0.707 (0.021),0.721 (0.014),0.742 (0.011),0.74 (0.01),0.744 (0.01),0.747 (0.011),0.748 (0.012)
3,star,0.69 (0.017),0.699 (0.012),0.687 (0.014),0.69 (0.014),0.691 (0.012),0.699 (0.011),0.701 (0.017)
4,winered,0.694 (0.022),0.698 (0.021),0.708 (0.021),0.71 (0.019),0.703 (0.02),0.704 (0.016),0.696 (0.023)
5,cycle,0.728 (0.009),0.76 (0.007),0.775 (0.009),0.774 (0.008),0.775 (0.009),0.786 (0.006),0.784 (0.008)
6,electric,0.773 (0.008),0.78 (0.007),0.738 (0.008),0.723 (0.01),0.724 (0.011),0.706 (0.01),0.785 (0.008)
7,meps19,0.767 (0.015),0.787 (0.016),0.779 (0.015),0.778 (0.018),0.783 (0.015),0.691 (0.008),0.804 (0.008)

### QNN scarcity worst coverage

,Dataset,credo_QNN,credo_QNN_adaptive,cqr,cqrr,uacqrs,uacqrp,EPIC
0,concrete,0.83 (0.015),0.845 (0.017),0.793 (0.021),0.794 (0.023),0.798 (0.022),0.811 (0.021),0.823 (0.022)
1,airfoil,0.857 (0.011),0.849 (0.014),0.844 (0.021),0.84 (0.021),0.838 (0.021),0.834 (0.019),0.859 (0.023)
2,winewhite,0.87 (0.008),0.877 (0.006),0.871 (0.009),0.869 (0.009),0.875 (0.008),0.872 (0.008),0.878 (0.01)
3,star,0.873 (0.009),0.87 (0.009),0.862 (0.01),0.869 (0.01),0.866 (0.008),0.874 (0.009),0.87 (0.012)
4,winered,0.854 (0.015),0.858 (0.013),0.858 (0.014),0.861 (0.013),0.86 (0.013),0.854 (0.014),0.862 (0.015)
5,cycle,0.876 (0.004),0.882 (0.004),0.876 (0.005),0.876 (0.005),0.873 (0.005),0.878 (0.004),0.878 (0.007)
6,electric,0.873 (0.006),0.868 (0.008),0.837 (0.009),0.832 (0.008),0.822 (0.01),0.821 (0.006),0.848 (0.009)
7,meps19,0.859 (0.009),0.866 (0.011),0.863 (0.007),0.86 (0.009),0.864 (0.007),0.775 (0.006),0.877 (0.006)

### QNN scarcity coverage - Q3

,Dataset,credo_QNN,credo_QNN_adaptive,cqr,cqrr,uacqrs,uacqrp,EPIC
0,concrete,0.893 (0.023),0.899 (0.017),0.916 (0.016),0.912 (0.014),0.908 (0.017),0.902 (0.018),0.902 (0.02)
1,airfoil,0.921 (0.015),0.918 (0.012),0.925 (0.014),0.928 (0.013),0.923 (0.014),0.933 (0.011),0.92 (0.015)
2,winewhite,0.905 (0.008),0.9 (0.008),0.897 (0.006),0.896 (0.005),0.898 (0.005),0.896 (0.007),0.895 (0.009)
3,star,0.899 (0.012),0.91 (0.011),0.896 (0.012),0.9 (0.011),0.9 (0.01),0.909 (0.009),0.911 (0.013)
4,winered,0.922 (0.018),0.917 (0.016),0.907 (0.015),0.904 (0.015),0.903 (0.015),0.899 (0.017),0.899 (0.016)
5,cycle,0.881 (0.005),0.892 (0.005),0.894 (0.005),0.893 (0.006),0.894 (0.006),0.897 (0.005),0.894 (0.007)
6,electric,0.904 (0.005),0.911 (0.005),0.895 (0.005),0.893 (0.006),0.893 (0.005),0.897 (0.006),0.897 (0.006)
7,meps19,0.887 (0.009),0.893 (0.009),0.891 (0.008),0.893 (0.008),0.891 (0.007),0.905 (0.004),0.887 (0.007)

### QNN scarcity coverage - Q4

,Dataset,credo_QNN,credo_QNN_adaptive,cqr,cqrr,uacqrs,uacqrp,EPIC
0,concrete,0.847 (0.019),0.858 (0.02),0.795 (0.022),0.796 (0.024),0.802 (0.024),0.817 (0.024),0.83 (0.025)
1,airfoil,0.942 (0.012),0.941 (0.012),0.851 (0.023),0.849 (0.023),0.845 (0.024),0.844 (0.022),0.875 (0.027)
2,winewhite,0.898 (0.008),0.907 (0.008),0.875 (0.011),0.873 (0.011),0.88 (0.01),0.875 (0.009),0.886 (0.012)
3,star,0.918 (0.01),0.921 (0.012),0.898 (0.012),0.897 (0.01),0.894 (0.01),0.905 (0.01),0.913 (0.016)
4,winered,0.904 (0.012),0.903 (0.012),0.869 (0.015),0.874 (0.015),0.876 (0.015),0.87 (0.014),0.878 (0.016)
5,cycle,0.894 (0.004),0.911 (0.004),0.88 (0.006),0.881 (0.005),0.876 (0.005),0.883 (0.005),0.887 (0.007)
6,electric,0.875 (0.006),0.903 (0.005),0.837 (0.009),0.832 (0.008),0.822 (0.01),0.821 (0.006),0.848 (0.009)
7,meps19,0.929 (0.01),0.917 (0.01),0.877 (0.009),0.876 (0.01),0.877 (0.009),0.775 (0.006),0.893 (0.006)

### QNN outlier coverage

,Dataset,credo_QNN,credo_QNN_adaptive,cqr,cqrr,uacqrs,uacqrp,EPIC
0,concrete,0.903 (0.031),0.921 (0.031),0.93 (0.026),0.924 (0.026),0.927 (0.028),0.927 (0.028),0.936 (0.026)
1,airfoil,0.891 (0.034),0.884 (0.03),0.887 (0.038),0.884 (0.038),0.882 (0.039),0.88 (0.036),0.898 (0.024)
2,winewhite,0.912 (0.016),0.909 (0.014),0.89 (0.013),0.891 (0.014),0.894 (0.015),0.89 (0.014),0.891 (0.014)
3,star,0.883 (0.019),0.871 (0.022),0.858 (0.021),0.858 (0.021),0.868 (0.02),0.877 (0.026),0.877 (0.024)
4,winered,0.902 (0.029),0.892 (0.032),0.9 (0.027),0.898 (0.027),0.902 (0.028),0.883 (0.029),0.89 (0.028)
5,cycle,0.888 (0.014),0.904 (0.011),0.867 (0.014),0.868 (0.014),0.865 (0.014),0.87 (0.015),0.869 (0.014)
6,electric,0.886 (0.011),0.888 (0.013),0.898 (0.015),0.901 (0.013),0.904 (0.012),0.908 (0.011),0.888 (0.014)
7,meps19,0.899 (0.009),0.895 (0.01),0.897 (0.007),0.898 (0.007),0.896 (0.008),0.893 (0.011),0.893 (0.008)

### QNN outlier/inlier ratio

,Dataset,credo_QNN,credo_QNN_adaptive,cqr,cqrr,uacqrs,uacqrp,EPIC
0,concrete,1.1 (0.06),1.149 (0.064),0.983 (0.051),0.976 (0.055),1.01 (0.052),0.983 (0.044),1.093 (0.071)
1,airfoil,1.213 (0.095),1.194 (0.089),1.161 (0.087),1.146 (0.08),1.146 (0.082),1.116 (0.076),1.175 (0.084)
2,winewhite,1.116 (0.032),1.121 (0.028),1.042 (0.018),1.045 (0.019),1.056 (0.017),1.031 (0.017),1.068 (0.022)
3,star,0.996 (0.015),0.99 (0.013),1.006 (0.014),1.007 (0.017),1.006 (0.018),0.996 (0.02),1.013 (0.014)
4,winered,1.236 (0.05),1.23 (0.056),1.129 (0.048),1.149 (0.057),1.174 (0.056),1.128 (0.043),1.193 (0.051)
5,cycle,1.001 (0.022),1.045 (0.017),0.903 (0.013),0.908 (0.013),0.896 (0.013),0.893 (0.013),0.908 (0.014)
6,electric,0.963 (0.023),0.96 (0.021),0.976 (0.023),0.982 (0.018),0.983 (0.021),0.983 (0.018),0.957 (0.029)
7,meps19,1.128 (0.073),1.126 (0.072),1.05 (0.046),1.051 (0.046),1.05 (0.046),1.024 (0.038),1.057 (0.05)

## QNN outlier metrics with Isolation Forest

The two tables below use the same QNN benchmark datasets from the new analysis and the Isolation Forest outlier/inlier split.

In [ ]:
qnn_outlier_if_table_files = {
    "Outlier coverage - Isolation Forest": "result_qnn_coverage_outlier_isolation_forest.pkl",
    "Outlier/inlier interval-length ratio - Isolation Forest": "result_qnn_ratio_outlier_isolation_forest.pkl",
}

qnn_outlier_if_tables = {}
for title, filename in qnn_outlier_if_table_files.items():
    table = order_qnn_datasets(pd.read_pickle(folder_path / filename))
    qnn_outlier_if_tables[title] = table
    display(Markdown(f"### {title}"))
    display(table)

QNN Isolation Forest LaTeX tables generated from the same dataframes:

In [ ]:
for title, table in qnn_outlier_if_tables.items():
    print(f"% {title}")
    custom_table_generator(table)
    print()

QNN LaTeX tables generated from the same dataframes:

In [4]:
for title, table in qnn_tables.items():
    print(f"% {title}")
    custom_table_generator(table)
    print()

% QNN SMIS
\begin{tabular}{lccccccc}\toprule
Dataset & credo_QNN & credo_QNN_adaptive & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
concrete & 27.259 (0.772) & 26.962 (0.802) & 26.819 (0.996) & 26.951 (1.026) & 26.602 (0.971) & 25.836 (0.79) & 26.41 (0.858)\\
airfoil & 11.497 (0.333) & 11.329 (0.331) & 8.995 (0.31) & 9.004 (0.308) & 9.038 (0.309) & 8.915 (0.296) & 8.87 (0.278)\\
winewhite & 3.002 (0.027) & 2.873 (0.029) & 2.959 (0.031) & 2.969 (0.03) & 2.958 (0.03) & 2.896 (0.033) & 2.966 (0.031)\\
star & 995.35 (14.778) & 976.693 (15.42) & 994.844 (12.668) & 1017.103 (12.741) & 1015.037 (13.59) & 988.443 (14.273) & 1009.792 (12.929)\\
winered & 2.722 (0.047) & 2.65 (0.055) & 2.713 (0.052) & 2.731 (0.054) & 2.708 (0.053) & 2.686 (0.053) & 2.743 (0.054)\\
cycle & 18.413 (0.212) & 17.696 (0.16) & 15.97 (0.178) & 15.958 (0.18) & 15.976 (0.178) & 15.707 (0.165) & 15.955 (0.178)\\
electric & 0.038 (0.0) & 0.038 (0.001) & 0.033 (0.0) & 0.033 (0.0) & 0.033 (0.0) & 0.032 (0.0) & 0.031 (0.0)\\
meps19 & 61.267 (1.242) & 57.698 (1.613) & 63.232 (2.256) & 63.278 (2.231) & 63.395 (2.375) & 68.899 (2.477) & 62.612 (2.174)\\
\bottomrule\end{tabular}

% QNN interval length
\begin{tabular}{lccccccc}\toprule
Dataset & credo_QNN & credo_QNN_adaptive & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
concrete & 21.55 (0.563) & 21.181 (0.486) & 18.91 (0.57) & 19.095 (0.61) & 18.835 (0.562) & 18.4 (0.516) & 19.067 (0.87)\\
airfoil & 9.404 (0.254) & 9.114 (0.196) & 6.807 (0.194) & 6.783 (0.195) & 6.769 (0.201) & 6.463 (0.166) & 6.8 (0.301)\\
winewhite & 2.496 (0.036) & 2.283 (0.02) & 2.218 (0.023) & 2.234 (0.025) & 2.233 (0.024) & 2.152 (0.021) & 2.24 (0.043)\\
star & 827.402 (10.993) & 813.281 (9.247) & 810.629 (10.009) & 832.042 (11.528) & 829.841 (10.42) & 817.904 (10.641) & 837.018 (21.906)\\
winered & 2.2 (0.038) & 2.026 (0.04) & 2.009 (0.034) & 2.039 (0.04) & 2.015 (0.036) & 1.994 (0.037) & 2.043 (0.08)\\
cycle & 14.342 (0.145) & 13.827 (0.135) & 11.945 (0.093) & 11.93 (0.096) & 11.946 (0.095) & 11.857 (0.082) & 11.912 (0.168)\\
electric & 0.031 (0.001) & 0.03 (0.001) & 0.024 (0.0) & 0.023 (0.0) & 0.024 (0.0) & 0.022 (0.0) & 0.023 (0.0)\\
meps19 & 47.414 (0.773) & 39.546 (0.746) & 29.487 (1.063) & 29.408 (1.156) & 29.327 (1.049) & 21.816 (0.335) & 30.321 (1.057)\\
\bottomrule\end{tabular}

% QNN WSC
\begin{tabular}{lccccccc}\toprule
Dataset & credo_QNN & credo_QNN_adaptive & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
concrete & 0.721 (0.025) & 0.741 (0.019) & 0.721 (0.021) & 0.721 (0.021) & 0.718 (0.022) & 0.724 (0.02) & 0.724 (0.024)\\
airfoil & 0.689 (0.019) & 0.695 (0.02) & 0.699 (0.025) & 0.698 (0.025) & 0.691 (0.027) & 0.701 (0.025) & 0.715 (0.03)\\
winewhite & 0.707 (0.021) & 0.721 (0.014) & 0.742 (0.011) & 0.74 (0.01) & 0.744 (0.01) & 0.747 (0.011) & 0.748 (0.012)\\
star & 0.69 (0.017) & 0.699 (0.012) & 0.687 (0.014) & 0.69 (0.014) & 0.691 (0.012) & 0.699 (0.011) & 0.701 (0.017)\\
winered & 0.694 (0.022) & 0.698 (0.021) & 0.708 (0.021) & 0.71 (0.019) & 0.703 (0.02) & 0.704 (0.016) & 0.696 (0.023)\\
cycle & 0.728 (0.009) & 0.76 (0.007) & 0.775 (0.009) & 0.774 (0.008) & 0.775 (0.009) & 0.786 (0.006) & 0.784 (0.008)\\
electric & 0.773 (0.008) & 0.78 (0.007) & 0.738 (0.008) & 0.723 (0.01) & 0.724 (0.011) & 0.706 (0.01) & 0.785 (0.008)\\
meps19 & 0.767 (0.015) & 0.787 (0.016) & 0.779 (0.015) & 0.778 (0.018) & 0.783 (0.015) & 0.691 (0.008) & 0.804 (0.008)\\
\bottomrule\end{tabular}

% QNN scarcity worst coverage
\begin{tabular}{lccccccc}\toprule
Dataset & credo_QNN & credo_QNN_adaptive & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
concrete & 0.83 (0.015) & 0.845 (0.017) & 0.793 (0.021) & 0.794 (0.023) & 0.798 (0.022) & 0.811 (0.021) & 0.823 (0.022)\\
airfoil & 0.857 (0.011) & 0.849 (0.014) & 0.844 (0.021) & 0.84 (0.021) & 0.838 (0.021) & 0.834 (0.019) & 0.859 (0.023)\\
winewhite & 0.87 (0.008) & 0.877 (0.006) & 0.871 (0.009) & 0.869 (0.009) & 0.875 (0.008) & 0.872 (0.008) & 0.878 (0.01)\\
star & 0.873 (0.009) & 0.87 (0.009) & 0.862 (0.01) & 0.869 (0.01) & 0.866 (0.008) & 0.874 (0.009) & 0.87 (0.012)\\
winered & 0.854 (0.015) & 0.858 (0.013) & 0.858 (0.014) & 0.861 (0.013) & 0.86 (0.013) & 0.854 (0.014) & 0.862 (0.015)\\
cycle & 0.876 (0.004) & 0.882 (0.004) & 0.876 (0.005) & 0.876 (0.005) & 0.873 (0.005) & 0.878 (0.004) & 0.878 (0.007)\\
electric & 0.873 (0.006) & 0.868 (0.008) & 0.837 (0.009) & 0.832 (0.008) & 0.822 (0.01) & 0.821 (0.006) & 0.848 (0.009)\\
meps19 & 0.859 (0.009) & 0.866 (0.011) & 0.863 (0.007) & 0.86 (0.009) & 0.864 (0.007) & 0.775 (0.006) & 0.877 (0.006)\\
\bottomrule\end{tabular}

% QNN scarcity coverage - Q3
\begin{tabular}{lccccccc}\toprule
Dataset & credo_QNN & credo_QNN_adaptive & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
concrete & 0.893 (0.023) & 0.899 (0.017) & 0.916 (0.016) & 0.912 (0.014) & 0.908 (0.017) & 0.902 (0.018) & 0.902 (0.02)\\
airfoil & 0.921 (0.015) & 0.918 (0.012) & 0.925 (0.014) & 0.928 (0.013) & 0.923 (0.014) & 0.933 (0.011) & 0.92 (0.015)\\
winewhite & 0.905 (0.008) & 0.9 (0.008) & 0.897 (0.006) & 0.896 (0.005) & 0.898 (0.005) & 0.896 (0.007) & 0.895 (0.009)\\
star & 0.899 (0.012) & 0.91 (0.011) & 0.896 (0.012) & 0.9 (0.011) & 0.9 (0.01) & 0.909 (0.009) & 0.911 (0.013)\\
winered & 0.922 (0.018) & 0.917 (0.016) & 0.907 (0.015) & 0.904 (0.015) & 0.903 (0.015) & 0.899 (0.017) & 0.899 (0.016)\\
cycle & 0.881 (0.005) & 0.892 (0.005) & 0.894 (0.005) & 0.893 (0.006) & 0.894 (0.006) & 0.897 (0.005) & 0.894 (0.007)\\
electric & 0.904 (0.005) & 0.911 (0.005) & 0.895 (0.005) & 0.893 (0.006) & 0.893 (0.005) & 0.897 (0.006) & 0.897 (0.006)\\
meps19 & 0.887 (0.009) & 0.893 (0.009) & 0.891 (0.008) & 0.893 (0.008) & 0.891 (0.007) & 0.905 (0.004) & 0.887 (0.007)\\
\bottomrule\end{tabular}

% QNN scarcity coverage - Q4
\begin{tabular}{lccccccc}\toprule
Dataset & credo_QNN & credo_QNN_adaptive & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
concrete & 0.847 (0.019) & 0.858 (0.02) & 0.795 (0.022) & 0.796 (0.024) & 0.802 (0.024) & 0.817 (0.024) & 0.83 (0.025)\\
airfoil & 0.942 (0.012) & 0.941 (0.012) & 0.851 (0.023) & 0.849 (0.023) & 0.845 (0.024) & 0.844 (0.022) & 0.875 (0.027)\\
winewhite & 0.898 (0.008) & 0.907 (0.008) & 0.875 (0.011) & 0.873 (0.011) & 0.88 (0.01) & 0.875 (0.009) & 0.886 (0.012)\\
star & 0.918 (0.01) & 0.921 (0.012) & 0.898 (0.012) & 0.897 (0.01) & 0.894 (0.01) & 0.905 (0.01) & 0.913 (0.016)\\
winered & 0.904 (0.012) & 0.903 (0.012) & 0.869 (0.015) & 0.874 (0.015) & 0.876 (0.015) & 0.87 (0.014) & 0.878 (0.016)\\
cycle & 0.894 (0.004) & 0.911 (0.004) & 0.88 (0.006) & 0.881 (0.005) & 0.876 (0.005) & 0.883 (0.005) & 0.887 (0.007)\\
electric & 0.875 (0.006) & 0.903 (0.005) & 0.837 (0.009) & 0.832 (0.008) & 0.822 (0.01) & 0.821 (0.006) & 0.848 (0.009)\\
meps19 & 0.929 (0.01) & 0.917 (0.01) & 0.877 (0.009) & 0.876 (0.01) & 0.877 (0.009) & 0.775 (0.006) & 0.893 (0.006)\\
\bottomrule\end{tabular}

% QNN outlier coverage
\begin{tabular}{lccccccc}\toprule
Dataset & credo_QNN & credo_QNN_adaptive & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
concrete & 0.903 (0.031) & 0.921 (0.031) & 0.93 (0.026) & 0.924 (0.026) & 0.927 (0.028) & 0.927 (0.028) & 0.936 (0.026)\\
airfoil & 0.891 (0.034) & 0.884 (0.03) & 0.887 (0.038) & 0.884 (0.038) & 0.882 (0.039) & 0.88 (0.036) & 0.898 (0.024)\\
winewhite & 0.912 (0.016) & 0.909 (0.014) & 0.89 (0.013) & 0.891 (0.014) & 0.894 (0.015) & 0.89 (0.014) & 0.891 (0.014)\\
star & 0.883 (0.019) & 0.871 (0.022) & 0.858 (0.021) & 0.858 (0.021) & 0.868 (0.02) & 0.877 (0.026) & 0.877 (0.024)\\
winered & 0.902 (0.029) & 0.892 (0.032) & 0.9 (0.027) & 0.898 (0.027) & 0.902 (0.028) & 0.883 (0.029) & 0.89 (0.028)\\
cycle & 0.888 (0.014) & 0.904 (0.011) & 0.867 (0.014) & 0.868 (0.014) & 0.865 (0.014) & 0.87 (0.015) & 0.869 (0.014)\\
electric & 0.886 (0.011) & 0.888 (0.013) & 0.898 (0.015) & 0.901 (0.013) & 0.904 (0.012) & 0.908 (0.011) & 0.888 (0.014)\\
meps19 & 0.899 (0.009) & 0.895 (0.01) & 0.897 (0.007) & 0.898 (0.007) & 0.896 (0.008) & 0.893 (0.011) & 0.893 (0.008)\\
\bottomrule\end{tabular}

% QNN outlier/inlier ratio
\begin{tabular}{lccccccc}\toprule
Dataset & credo_QNN & credo_QNN_adaptive & cqr & cqrr & uacqrs & uacqrp & EPIC\\\midrule
concrete & 1.1 (0.06) & 1.149 (0.064) & 0.983 (0.051) & 0.976 (0.055) & 1.01 (0.052) & 0.983 (0.044) & 1.093 (0.071)\\
airfoil & 1.213 (0.095) & 1.194 (0.089) & 1.161 (0.087) & 1.146 (0.08) & 1.146 (0.082) & 1.116 (0.076) & 1.175 (0.084)\\
winewhite & 1.116 (0.032) & 1.121 (0.028) & 1.042 (0.018) & 1.045 (0.019) & 1.056 (0.017) & 1.031 (0.017) & 1.068 (0.022)\\
star & 0.996 (0.015) & 0.99 (0.013) & 1.006 (0.014) & 1.007 (0.017) & 1.006 (0.018) & 0.996 (0.02) & 1.013 (0.014)\\
winered & 1.236 (0.05) & 1.23 (0.056) & 1.129 (0.048) & 1.149 (0.057) & 1.174 (0.056) & 1.128 (0.043) & 1.193 (0.051)\\
cycle & 1.001 (0.022) & 1.045 (0.017) & 0.903 (0.013) & 0.908 (0.013) & 0.896 (0.013) & 0.893 (0.013) & 0.908 (0.014)\\
electric & 0.963 (0.023) & 0.96 (0.021) & 0.976 (0.023) & 0.982 (0.018) & 0.983 (0.021) & 0.983 (0.018) & 0.957 (0.029)\\
meps19 & 1.128 (0.073) & 1.126 (0.072) & 1.05 (0.046) & 1.051 (0.046) & 1.05 (0.046) & 1.024 (0.038) & 1.057 (0.05)\\
\bottomrule\end{tabular}

If you prefer to use the already written `.tex` files directly:

In [ ]:
from pathlib import Path

project_root = Path.cwd()
if project_root.name == "comparisons":
    project_root = project_root.parent

folder_path = project_root / "results" / "final_tables"
tex_name = "result_qnn_smis.tex"
print((folder_path / tex_name).read_text())